<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Business;

class BusinessesRisikoSeeder2026 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $business=new business();           $business->business_code = '2026-RIS029-001';          $business->index = '1';             $business->description = 'Non-Proportional Facultative Reinsurance Contract – All Risks';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Third party';                $business->premium_type = 'Fixed';               $business->purpose = 'Traditional';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '36';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '109';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-01-15'));           $business->business_lifecycle_status = 'In Force';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-01-15'));            $business->source_code = null;             $business->created_by_user =  '18 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-01-15'));           $business->save(); 
        $business=new business();           $business->business_code = '2026-RIS029-002';          $business->index = '2';             $business->description = 'Non-Proportional Facultative Reinsurance Contract – All Risks';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Third party';                $business->premium_type = 'Fixed';               $business->purpose = 'Traditional';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '36';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '109';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-01-15'));           $business->business_lifecycle_status = 'In Force';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-01-15'));            $business->source_code = null;             $business->created_by_user =  '18 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-01-15'));           $business->save(); 
        $business=new business();           $business->business_code = '2026-RIS029-003';          $business->index = '3';             $business->description = 'Non-Proportional Facultative Liability Reinsurance Contract';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Third party';                $business->premium_type = 'Fixed';               $business->purpose = 'Traditional';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '36';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '109';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-01-15'));           $business->business_lifecycle_status = 'In Force';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-01-15'));            $business->source_code = null;             $business->created_by_user =  '18 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-01-15'));           $business->save(); 
        $business=new business();           $business->business_code = '2026-RIS029-004';          $business->index = '4';             $business->description = 'Non-Proportional Facultative Reinsurance Contract – All Risks';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Third party';                $business->premium_type = 'Fixed';               $business->purpose = 'Traditional';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '36';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '109';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-01-15'));           $business->business_lifecycle_status = 'In Force';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-01-15'));            $business->source_code = null;             $business->created_by_user =  '18 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-01-15'));           $business->save(); 
        $business=new business();           $business->business_code = '2026-RIS029-005';          $business->index = '5';             $business->description = 'Non-Proportional Facultative Liability Reinsurance Contract';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Third party';                $business->premium_type = 'Fixed';               $business->purpose = 'Traditional';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '36';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '109';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-01-30'));           $business->business_lifecycle_status = 'In Force';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-01-30'));            $business->source_code = null;             $business->created_by_user =  '18 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-01-30'));           $business->save(); 
    }
}
