<?php

namespace Database\Seeders;

use App\Models\OperativeDoc;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessesDocsZamaSeeder2025 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2025-ZMA056-001-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance – Non-Proportional Automatic Surety Reinsurance Contract (Working Cover).';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2024-12-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-11-25'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2025-ZMA056-001-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '16' ;                              $OperativeDoc->business_code = '2025-ZMA056-001';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2024-12-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime('2024-12-01'));       $OperativeDoc->rep_date = date('Y-m-d',strtotime('2025-08-01'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2025-ZMA056-002-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract  for Key Man';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2025-12-31'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-12-31'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2025-ZMA056-002-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '16' ;                              $OperativeDoc->business_code = '2025-ZMA056-002';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2025-12-31'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime('2025-12-31'));       $OperativeDoc->rep_date = date('Y-m-d',strtotime('2025-12-01'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2025-ZMA056-003-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract for Directors and Officers Liability';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2025-12-31'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-08-16'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2025-ZMA056-003-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '16' ;                              $OperativeDoc->business_code = '2025-ZMA056-003';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2025-12-31'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime('2025-12-31'));       $OperativeDoc->rep_date = date('Y-m-d',strtotime('2025-12-01'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2025-ZMA056-004-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract  for All Risk';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-12-31'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2025-ZMA056-004-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '16' ;                              $OperativeDoc->business_code = '2025-ZMA056-004';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime('2026-01-01'));       $OperativeDoc->rep_date = date('Y-m-d',strtotime('2026-01-01'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2025-ZMA056-004-02';         $OperativeDoc->operative_doc_type_id = '5';        $OperativeDoc->index = '2';         $OperativeDoc->description = 'Facultative Reinsurance Contract  for All Risk';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-12-31'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2025-ZMA056-004-02.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '16' ;                              $OperativeDoc->business_code = '2025-ZMA056-004';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime('2026-01-01'));       $OperativeDoc->rep_date = date('Y-m-d',strtotime('2026-01-01'));        $OperativeDoc->save(); 
    }
}