<?php

namespace Database\Seeders;

use App\Models\OperativeDoc;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessesDocsInvictusSeeder2026 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-INV039-001-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract Cancellation for Political Violence.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-06-30'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-INV039-001-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-INV039-001';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-INV039-001-02';         $OperativeDoc->operative_doc_type_id = '5';        $OperativeDoc->index = '2';         $OperativeDoc->description = 'Facultative Reinsurance Contract Cancellation for Political Violence.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-06-30'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-INV039-001-02.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-INV039-001';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-INV039-002-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract Cancellation for Political Violence.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-06-30'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-INV039-002-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-INV039-002';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-INV039-002-02';         $OperativeDoc->operative_doc_type_id = '5';        $OperativeDoc->index = '2';         $OperativeDoc->description = 'Facultative Reinsurance Contract Cancellation for Political Violence.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-06-30'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-INV039-002-02.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-INV039-002';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-INV039-003-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract Cancellation for Terrorism.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-06-30'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-INV039-003-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-INV039-003';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-INV039-003-02';         $OperativeDoc->operative_doc_type_id = '5';        $OperativeDoc->index = '2';         $OperativeDoc->description = 'Facultative Reinsurance Contract Cancellation for Terrorism.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-06-30'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-INV039-003-02.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-INV039-003';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-INV039-004-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract Cancellation for Terrorism.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-06-30'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-INV039-004-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-INV039-004';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-INV039-004-02';         $OperativeDoc->operative_doc_type_id = '5';        $OperativeDoc->index = '2';         $OperativeDoc->description = 'Facultative Reinsurance Contract Cancellation for Terrorism.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-06-30'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-INV039-004-02.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-INV039-004';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-INV039-005-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract Cancellation for Political Violence.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-12-31'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-INV039-005-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-INV039-005';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-INV039-006-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract Cancellation for Political Violence.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-12-31'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-INV039-006-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-INV039-006';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-INV039-007-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract Cancellation for Terrorism.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-12-31'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-INV039-007-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-INV039-007';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-INV039-008-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract Cancellation for Terrorism.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-01-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2026-12-31'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-INV039-008-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-INV039-008';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save();           

    }
}