<?php

namespace Database\Seeders;

use App\Models\BusinessOpDocs;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessesDocsAdamasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $BusinessOpDocs=new BusinessOpDocs();          $BusinessOpDocs->id = '2014-ADA005-001-01';         $BusinessOpDocs->BusinessOpDocs_type_id = '1';        $BusinessOpDocs->index = '1';         $BusinessOpDocs->description = 'Facultative Reinsurance Contract';         $BusinessOpDocs->inception_date = date('Y-m-d',strtotime('2014-12-22'));         $BusinessOpDocs->expiration_date = date('Y-m-d',strtotime('2015-12-22'));         $BusinessOpDocs->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/BusinessOpDocsuments/2014-ADA005-001-01.pdf ' ;              $BusinessOpDocs->roe = '1';           $BusinessOpDocs->business_code = '2014-ADA005-001';            $BusinessOpDocs->created_at = date('Y-m-d',strtotime('2014-12-26'));        $BusinessOpDocs->save(); 
        $BusinessOpDocs=new BusinessOpDocs();          $BusinessOpDocs->id = '2014-ADA005-002-01';         $BusinessOpDocs->BusinessOpDocs_type_id = '1';        $BusinessOpDocs->index = '1';         $BusinessOpDocs->description = 'Facultative Reinsurance Contract';         $BusinessOpDocs->inception_date = date('Y-m-d',strtotime('2015-04-15'));         $BusinessOpDocs->expiration_date = date('Y-m-d',strtotime('2016-04-15'));         $BusinessOpDocs->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/BusinessOpDocsuments/2014-ADA005-002-01.pdf ' ;              $BusinessOpDocs->roe = '1';           $BusinessOpDocs->business_code = '2014-ADA005-002';            $BusinessOpDocs->created_at = date('Y-m-d',strtotime('2015-09-09'));        $BusinessOpDocs->save(); 
        $BusinessOpDocs=new BusinessOpDocs();          $BusinessOpDocs->id = '2015-ADA005-001-01';         $BusinessOpDocs->BusinessOpDocs_type_id = '1';        $BusinessOpDocs->index = '1';         $BusinessOpDocs->description = 'Facultative Reinsurance Contract';         $BusinessOpDocs->inception_date = date('Y-m-d',strtotime('2015-04-15'));         $BusinessOpDocs->expiration_date = date('Y-m-d',strtotime('2016-04-15'));         $BusinessOpDocs->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/BusinessOpDocsuments/2015-ADA005-001-01.pdf ' ;              $BusinessOpDocs->roe = '1';           $BusinessOpDocs->business_code = '2015-ADA005-001';            $BusinessOpDocs->created_at = date('Y-m-d',strtotime('2015-09-09'));        $BusinessOpDocs->save(); 
        $BusinessOpDocs=new BusinessOpDocs();          $BusinessOpDocs->id = '2015-ADA005-002-01';         $BusinessOpDocs->BusinessOpDocs_type_id = '1';        $BusinessOpDocs->index = '1';         $BusinessOpDocs->description = 'Facultative Reinsurance Contract';         $BusinessOpDocs->inception_date = date('Y-m-d',strtotime('2015-09-01'));         $BusinessOpDocs->expiration_date = date('Y-m-d',strtotime('2016-09-01'));         $BusinessOpDocs->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/BusinessOpDocsuments/2015-ADA005-002-01.pdf ' ;              $BusinessOpDocs->roe = '1';           $BusinessOpDocs->business_code = '2015-ADA005-002';            $BusinessOpDocs->created_at = date('Y-m-d',strtotime('2015-12-24'));        $BusinessOpDocs->save(); 
        $BusinessOpDocs=new BusinessOpDocs();          $BusinessOpDocs->id = '2015-ADA005-003-01';         $BusinessOpDocs->BusinessOpDocs_type_id = '1';        $BusinessOpDocs->index = '1';         $BusinessOpDocs->description = 'Facultative Reinsurance Contract';         $BusinessOpDocs->inception_date = date('Y-m-d',strtotime('2015-12-22'));         $BusinessOpDocs->expiration_date = date('Y-m-d',strtotime('2016-12-22'));         $BusinessOpDocs->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/BusinessOpDocsuments/2015-ADA005-003-01.pdf ' ;              $BusinessOpDocs->roe = '1';           $BusinessOpDocs->business_code = '2015-ADA005-003';            $BusinessOpDocs->created_at = date('Y-m-d',strtotime('2015-12-24'));        $BusinessOpDocs->save(); 
        $BusinessOpDocs=new BusinessOpDocs();          $BusinessOpDocs->id = '2016-ADA005-001-01';         $BusinessOpDocs->BusinessOpDocs_type_id = '1';        $BusinessOpDocs->index = '1';         $BusinessOpDocs->description = 'Facultative Reinsurance Contract';         $BusinessOpDocs->inception_date = date('Y-m-d',strtotime('2015-05-04'));         $BusinessOpDocs->expiration_date = date('Y-m-d',strtotime('2016-05-04'));         $BusinessOpDocs->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/BusinessOpDocsuments/2016-ADA005-001-01.pdf ' ;              $BusinessOpDocs->roe = '1';           $BusinessOpDocs->business_code = '2016-ADA005-001';            $BusinessOpDocs->created_at = date('Y-m-d',strtotime('2016-03-30'));        $BusinessOpDocs->save(); 
    }
}
