<?php

namespace Database\Seeders;

use App\Models\OperativeDoc;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessesDocsCellMayabSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2010-CMY001-001-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2010-12-31'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2011-12-31'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2010-CMY001-001-01.pdf ' ;               $OperativeDoc->business_code = '2010-CMY001-001';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2010-12-31'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2011-CMY001-001-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2011-12-31'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2012-12-31'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2011-CMY001-001-01.pdf ' ;               $OperativeDoc->business_code = '2011-CMY001-001';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2011-12-31'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2011-CMY001-001-02';         $OperativeDoc->operative_doc_type_id = '3';        $OperativeDoc->index = '2';         $OperativeDoc->description = 'Change in installment dates.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2011-12-31'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2012-12-31'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2011-CMY001-001-02.pdf ' ;               $OperativeDoc->business_code = '2011-CMY001-001';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2012-01-05'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2011-CMY001-002-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2011-09-30'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2012-09-30'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2011-CMY001-002-01.pdf ' ;               $OperativeDoc->business_code = '2011-CMY001-002';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2011-09-30'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2011-CMY001-002-02';         $OperativeDoc->operative_doc_type_id = '2';        $OperativeDoc->index = '2';         $OperativeDoc->description = 'It is agreed, a coverage extension period of 1 year.';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2012-09-30'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2013-09-30'));         $OperativeDoc->document_path = null;              $OperativeDoc->business_code = '2011-CMY001-002';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2012-09-30'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2012-CMY001-001-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2012-12-31'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2013-12-31'));         $OperativeDoc->document_path = null;              $OperativeDoc->business_code = '2012-CMY001-001';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2012-12-31'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2012-CMY001-002-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2012-07-05'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2013-07-05'));         $OperativeDoc->document_path = null;              $OperativeDoc->business_code = '2012-CMY001-002';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2012-07-05'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2012-CMY001-003-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2012-12-28'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2013-12-28'));         $OperativeDoc->document_path = null;              $OperativeDoc->business_code = '2012-CMY001-003';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2012-12-28'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2012-CMY001-004-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2012-12-28'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2013-12-28'));         $OperativeDoc->document_path = null;              $OperativeDoc->business_code = '2012-CMY001-004';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2012-12-28'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2013-CMY001-001-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2013-02-15'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2014-02-15'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2013-CMY001-001-01.pdf ' ;               $OperativeDoc->business_code = '2013-CMY001-001';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2013-02-15'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2013-CMY001-002-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2013-07-05'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2014-07-05'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2013-CMY001-002-01.pdf ' ;               $OperativeDoc->business_code = '2013-CMY001-002';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2013-07-05'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2013-CMY001-003-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2013-12-28'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2014-12-28'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2013-CMY001-003-01.pdf ' ;               $OperativeDoc->business_code = '2013-CMY001-003';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2013-12-28'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2013-CMY001-004-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2013-12-28'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2014-12-28'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2013-CMY001-004-01.pdf ' ;               $OperativeDoc->business_code = '2013-CMY001-004';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2013-12-28'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2014-CMY001-001-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2014-02-15'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2015-02-15'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2014-CMY001-001-01.pdf ' ;               $OperativeDoc->business_code = '2014-CMY001-001';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2014-02-15'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2014-CMY001-002-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2014-08-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2015-08-01'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2014-CMY001-002-01.pdf ' ;               $OperativeDoc->business_code = '2014-CMY001-002';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2014-08-01'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2014-CMY001-003-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2014-12-28'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2015-12-28'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2014-CMY001-003-01.pdf ' ;               $OperativeDoc->business_code = '2014-CMY001-003';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2014-12-28'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2014-CMY001-004-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2014-12-28'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2015-12-28'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2014-CMY001-004-01.pdf ' ;               $OperativeDoc->business_code = '2014-CMY001-004';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2014-12-28'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2015-CMY001-001-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2015-02-15'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2016-02-15'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2015-CMY001-001-01.pdf ' ;               $OperativeDoc->business_code = '2015-CMY001-001';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2015-02-15'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2015-CMY001-002-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2015-08-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2016-08-01'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2015-CMY001-002-01.pdf ' ;               $OperativeDoc->business_code = '2015-CMY001-002';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2015-08-01'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2015-CMY001-003-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2015-12-28'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2016-12-28'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2015-CMY001-003-01.pdf ' ;               $OperativeDoc->business_code = '2015-CMY001-003';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2015-12-28'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2015-CMY001-004-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2015-12-28'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2016-12-28'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2015-CMY001-004-01.pdf ' ;               $OperativeDoc->business_code = '2015-CMY001-004';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2015-12-28'));        $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2016-CMY001-001-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2016-02-15'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2017-02-15'));         $OperativeDoc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2016-CMY001-001-01.pdf ' ;               $OperativeDoc->business_code = '2016-CMY001-001';                  $OperativeDoc->created_at = date('Y-m-d',strtotime('2016-02-15'));        $OperativeDoc->save();  

    }
}
