<?php

namespace Database\Seeders;

use App\Models\business_doc;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessesDocsCellMayabSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $business_doc=new business_doc();          $business_doc->id = '2010-CMY001-001-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2010-12-31'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2011-12-31'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2010-CMY001-001-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2010-CMY001-001';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2010-12-31'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2011-CMY001-001-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2011-12-31'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2012-12-31'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2011-CMY001-001-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2011-CMY001-001';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2011-12-31'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2011-CMY001-001-02';         $business_doc->business_doc_type_id = '3';        $business_doc->index = '2';         $business_doc->description = 'Change in installment dates.';         $business_doc->inception_date = date('Y-m-d',strtotime('2011-12-31'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2012-12-31'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2011-CMY001-001-02.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2011-CMY001-001';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2012-01-05'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2011-CMY001-002-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2011-09-30'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2012-09-30'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2011-CMY001-002-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2011-CMY001-002';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2011-09-30'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2011-CMY001-002-02';         $business_doc->business_doc_type_id = '2';        $business_doc->index = '2';         $business_doc->description = 'It is agreed, a coverage extension period of 1 year.';         $business_doc->inception_date = date('Y-m-d',strtotime('2012-09-30'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2013-09-30'));         $business_doc->document_path = null;             $business_doc->roe = '1';           $business_doc->business_code = '2011-CMY001-002';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2012-09-30'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2012-CMY001-001-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2012-12-31'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2013-12-31'));         $business_doc->document_path = null;             $business_doc->roe = '1';           $business_doc->business_code = '2012-CMY001-001';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2012-12-31'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2012-CMY001-002-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2012-07-05'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2013-07-05'));         $business_doc->document_path = null;             $business_doc->roe = '1';           $business_doc->business_code = '2012-CMY001-002';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2012-07-05'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2012-CMY001-003-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2012-12-28'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2013-12-28'));         $business_doc->document_path = null;             $business_doc->roe = '1';           $business_doc->business_code = '2012-CMY001-003';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2012-12-28'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2012-CMY001-004-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2012-12-28'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2013-12-28'));         $business_doc->document_path = null;             $business_doc->roe = '1';           $business_doc->business_code = '2012-CMY001-004';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2012-12-28'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2013-CMY001-001-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2013-02-15'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2014-02-15'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2013-CMY001-001-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2013-CMY001-001';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2013-02-15'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2013-CMY001-002-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2013-07-05'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2014-07-05'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2013-CMY001-002-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2013-CMY001-002';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2013-07-05'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2013-CMY001-003-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2013-12-28'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2014-12-28'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2013-CMY001-003-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2013-CMY001-003';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2013-12-28'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2013-CMY001-004-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2013-12-28'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2014-12-28'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2013-CMY001-004-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2013-CMY001-004';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2013-12-28'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2014-CMY001-001-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2014-02-15'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2015-02-15'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2014-CMY001-001-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2014-CMY001-001';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2014-02-15'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2014-CMY001-002-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2014-08-01'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2015-08-01'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2014-CMY001-002-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2014-CMY001-002';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2014-08-01'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2014-CMY001-003-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2014-12-28'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2015-12-28'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2014-CMY001-003-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2014-CMY001-003';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2014-12-28'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2014-CMY001-004-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2014-12-28'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2015-12-28'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2014-CMY001-004-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2014-CMY001-004';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2014-12-28'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2015-CMY001-001-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2015-02-15'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2016-02-15'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2015-CMY001-001-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2015-CMY001-001';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2015-02-15'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2015-CMY001-002-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2015-08-01'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2016-08-01'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2015-CMY001-002-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2015-CMY001-002';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2015-08-01'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2015-CMY001-003-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2015-12-28'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2016-12-28'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2015-CMY001-003-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2015-CMY001-003';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2015-12-28'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2015-CMY001-004-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2015-12-28'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2016-12-28'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2015-CMY001-004-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2015-CMY001-004';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2015-12-28'));        $business_doc->save(); 
        $business_doc=new business_doc();          $business_doc->id = '2016-CMY001-001-01';         $business_doc->business_doc_type_id = '1';        $business_doc->index = '1';         $business_doc->description = 'Facultative Reinsurance Contract';         $business_doc->inception_date = date('Y-m-d',strtotime('2016-02-15'));         $business_doc->expiration_date = date('Y-m-d',strtotime('2017-02-15'));         $business_doc->document_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/business_documents/2016-CMY001-001-01.pdf ' ;              $business_doc->roe = '1';           $business_doc->business_code = '2016-CMY001-001';          $business_doc->client_payment_tracking = TRUE;        $business_doc->created_at = date('Y-m-d',strtotime('2016-02-15'));        $business_doc->save();  

    }
}
