<?php

namespace Database\Seeders;

use App\Models\OperativeDoc;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessesDocsMayabSeeder2026 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-MAY010-001-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-15'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-15'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-MAY010-001-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-MAY010-001';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-15'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-MAY010-002-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-15'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-15'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-MAY010-002-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-MAY010-002';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-15'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-MAY010-003-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance Contract';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-15'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-15'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-MAY010-003-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-MAY010-003';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-15'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-MAY010-004-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Proportional Facultative Reinsurance for Terrorism and Sabotage';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-15'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-15'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-MAY010-004-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-MAY010-004';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-15'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-MAY010-005-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Proportional Facultative Reinsurance for Miscellaneous Coverage';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-15'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-15'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-MAY010-005-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '15' ;                              $OperativeDoc->business_code = '2026-MAY010-005';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-15'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save();         

    }
}