<?php

namespace Database\Seeders;

use App\Models\Business;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessesAdamasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $Business=new Business();           $Business->Business_code = '2014-ADA005-001';          $Business->Index = '87';             $Business->description = 'Facultative Reinsurance Contract';         $Business->reinsurance_type = 'Facultative';         $Business->risk_covered = 'Non-Life';               $Business->Business_type = 'Own';                $Business->premium_type = 'Fixed';               $Business->purpose = 'Strategic';                  $Business->claims_type = 'Claims occurrence';              $Business->reinsurer_id = '7';                 $Business->parent_id = null;             $Business->renewed_from_id = null;             $Business->producer_id = '96';              $Business->currency_id = '157';                $Business->region_id = '2';              $Business->approval_status = 'APR';            $Business->approval_status_updated_at= date('Y-m-d',strtotime('2014-12-26'));           $Business->Business_lifecycle_status = 'Expired';         $Business->Business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2014-12-26'));           $Business->created_at = date('Y-m-d',strtotime('2014-12-26'));           $Business->save(); 
$Business=new Business();           $Business->Business_code = '2014-ADA005-002';          $Business->Index = '88';             $Business->description = 'Facultative Reinsurance Contract';         $Business->reinsurance_type = 'Facultative';         $Business->risk_covered = 'Non-Life';               $Business->Business_type = 'Own';                $Business->premium_type = 'Fixed';               $Business->purpose = 'Strategic';                  $Business->claims_type = 'Claims occurrence';              $Business->reinsurer_id = '7';                 $Business->parent_id = null;             $Business->renewed_from_id = null;             $Business->producer_id = '96';              $Business->currency_id = '157';                $Business->region_id = '2';              $Business->approval_status = 'APR';            $Business->approval_status_updated_at= date('Y-m-d',strtotime('2015-09-09'));           $Business->Business_lifecycle_status = 'Expired';         $Business->Business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2015-09-09'));           $Business->created_at = date('Y-m-d',strtotime('2015-09-09'));           $Business->save(); 
$Business=new Business();           $Business->Business_code = '2015-ADA005-001';          $Business->Index = '89';             $Business->description = 'Facultative Reinsurance Contract';         $Business->reinsurance_type = 'Facultative';         $Business->risk_covered = 'Non-Life';               $Business->Business_type = 'Own';                $Business->premium_type = 'Fixed';               $Business->purpose = 'Strategic';                  $Business->claims_type = 'Claims occurrence';              $Business->reinsurer_id = '7';                 $Business->parent_id = null;             $Business->renewed_from_id = null;             $Business->producer_id = '96';              $Business->currency_id = '157';                $Business->region_id = '2';              $Business->approval_status = 'APR';            $Business->approval_status_updated_at= date('Y-m-d',strtotime('2015-09-09'));           $Business->Business_lifecycle_status = 'Expired';         $Business->Business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2015-09-09'));           $Business->created_at = date('Y-m-d',strtotime('2015-09-09'));           $Business->save(); 
$Business=new Business();           $Business->Business_code = '2015-ADA005-002';          $Business->Index = '90';             $Business->description = 'Facultative Reinsurance Contract';         $Business->reinsurance_type = 'Facultative';         $Business->risk_covered = 'Non-Life';               $Business->Business_type = 'Own';                $Business->premium_type = 'Fixed';               $Business->purpose = 'Strategic';                  $Business->claims_type = 'Claims occurrence';              $Business->reinsurer_id = '7';                 $Business->parent_id = null;             $Business->renewed_from_id = null;             $Business->producer_id = '96';              $Business->currency_id = '157';                $Business->region_id = '2';              $Business->approval_status = 'APR';            $Business->approval_status_updated_at= date('Y-m-d',strtotime('2015-12-24'));           $Business->Business_lifecycle_status = 'Expired';         $Business->Business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2015-12-24'));           $Business->created_at = date('Y-m-d',strtotime('2015-12-24'));           $Business->save(); 
$Business=new Business();           $Business->Business_code = '2015-ADA005-003';          $Business->Index = '91';             $Business->description = 'Facultative Reinsurance Contract';         $Business->reinsurance_type = 'Facultative';         $Business->risk_covered = 'Non-Life';               $Business->Business_type = 'Own';                $Business->premium_type = 'Fixed';               $Business->purpose = 'Strategic';                  $Business->claims_type = 'Claims occurrence';              $Business->reinsurer_id = '7';                 $Business->parent_id = null;             $Business->renewed_from_id = null;             $Business->producer_id = '96';              $Business->currency_id = '157';                $Business->region_id = '2';              $Business->approval_status = 'APR';            $Business->approval_status_updated_at= date('Y-m-d',strtotime('2015-12-24'));           $Business->Business_lifecycle_status = 'Expired';         $Business->Business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2015-12-24'));           $Business->created_at = date('Y-m-d',strtotime('2015-12-24'));           $Business->save(); 
$Business=new Business();           $Business->Business_code = '2016-ADA005-001';          $Business->Index = '92';             $Business->description = 'Facultative Reinsurance Contract';         $Business->reinsurance_type = 'Facultative';         $Business->risk_covered = 'Non-Life';               $Business->Business_type = 'Own';                $Business->premium_type = 'Fixed';               $Business->purpose = 'Strategic';                  $Business->claims_type = 'Claims occurrence';              $Business->reinsurer_id = '7';                 $Business->parent_id = null;             $Business->renewed_from_id = null;             $Business->producer_id = '96';              $Business->currency_id = '157';                $Business->region_id = '2';              $Business->approval_status = 'APR';            $Business->approval_status_updated_at= date('Y-m-d',strtotime('2016-03-30'));           $Business->Business_lifecycle_status = 'Expired';         $Business->Business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2016-03-30'));           $Business->created_at = date('Y-m-d',strtotime('2016-03-30'));           $Business->save();     }
}
