<?php

namespace Database\Seeders;

use App\Models\Business;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessesInvictusSeeder2026 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $business=new business();           $business->business_code = '2026-INV039-001';          $business->index = '1';             $business->description = 'Facultative Reinsurance Contract Cancellation for Political Violence.';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '47';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-02-05'));           $business->business_lifecycle_status = 'Cancelled';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-02-01'));            $business->source_code = null;             $business->created_by_user =  '15 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-02-01'));           $business->save(); 
        $business=new business();           $business->business_code = '2026-INV039-002';          $business->index = '2';             $business->description = 'Facultative Reinsurance Contract Cancellation for Political Violence.';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '47';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-02-05'));           $business->business_lifecycle_status = 'Cancelled';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-02-01'));            $business->source_code = null;             $business->created_by_user =  '15 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-02-01'));           $business->save(); 
        $business=new business();           $business->business_code = '2026-INV039-003';          $business->index = '3';             $business->description = 'Facultative Reinsurance Contract Cancellation for Terrorism.';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '47';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-02-05'));           $business->business_lifecycle_status = 'Cancelled';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-02-01'));            $business->source_code = null;             $business->created_by_user =  '15 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-02-01'));           $business->save(); 
        $business=new business();           $business->business_code = '2026-INV039-004';          $business->index = '4';             $business->description = 'Facultative Reinsurance Contract Cancellation for Terrorism.';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '47';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-02-05'));           $business->business_lifecycle_status = 'Cancelled';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-02-01'));            $business->source_code = null;             $business->created_by_user =  '15 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-02-01'));           $business->save(); 
        $business=new business();           $business->business_code = '2026-INV039-005';          $business->index = '5';             $business->description = 'Facultative Reinsurance Contract Cancellation for Political Violence.';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '47';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-02-13'));           $business->business_lifecycle_status = 'In Force';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-02-13'));            $business->source_code = null;             $business->created_by_user =  '15 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-02-13'));           $business->save(); 
        $business=new business();           $business->business_code = '2026-INV039-006';          $business->index = '6';             $business->description = 'Facultative Reinsurance Contract Cancellation for Political Violence.';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '47';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-02-13'));           $business->business_lifecycle_status = 'In Force';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-02-13'));            $business->source_code = null;             $business->created_by_user =  '15 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-02-13'));           $business->save(); 
        $business=new business();           $business->business_code = '2026-INV039-007';          $business->index = '7';             $business->description = 'Facultative Reinsurance Contract Cancellation for Terrorism.';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '47';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-02-13'));           $business->business_lifecycle_status = 'In Force';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-02-13'));            $business->source_code = null;             $business->created_by_user =  '15 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-02-13'));           $business->save(); 
        $business=new business();           $business->business_code = '2026-INV039-008';          $business->index = '8';             $business->description = 'Facultative Reinsurance Contract Cancellation for Terrorism.';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '47';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-02-13'));           $business->business_lifecycle_status = 'In Force';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-02-13'));            $business->source_code = null;             $business->created_by_user =  '15 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-02-13'));           $business->save();   

    }
}