<?php

namespace Database\Seeders;

use App\Models\OperativeDoc;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessesDocsTobahSeeder2026 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-TOB014-001-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Proportional Facultative Reinsurance for Political Violence. ';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-01'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-TOB014-001-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '14' ;                              $OperativeDoc->business_code = '2026-TOB014-001';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-TOB014-002-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Proportional Facultative Reinsurance for Political Violence. ';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-01'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-TOB014-002-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '14' ;                              $OperativeDoc->business_code = '2026-TOB014-002';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-TOB014-003-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Proportional Facultative Reinsurance for Terrorism and Sabotage. ';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-01'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-TOB014-003-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '14' ;                              $OperativeDoc->business_code = '2026-TOB014-003';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-TOB014-004-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Proportional Facultative Reinsurance for Terrorism and Sabotage. ';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-01'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-TOB014-004-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '14' ;                              $OperativeDoc->business_code = '2026-TOB014-004';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-TOB014-005-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance for Fraudulent Acts (Crime). ';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-01'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-TOB014-005-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '14' ;                              $OperativeDoc->business_code = '2026-TOB014-005';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-TOB014-006-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Facultative Reinsurance for Fraudulent Acts (Crime). ';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-01'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-TOB014-006-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '14' ;                              $OperativeDoc->business_code = '2026-TOB014-006';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-TOB014-007-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Proportional Facultative Reinsurance for Business Interruption and Contingent Business Interruption. ';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-01'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-TOB014-007-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '14' ;                              $OperativeDoc->business_code = '2026-TOB014-007';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-TOB014-008-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Proportional Facultative Reinsurance for Business Interruption and Contingent Business Interruption. ';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-01'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-TOB014-008-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '14' ;                              $OperativeDoc->business_code = '2026-TOB014-008';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-TOB014-009-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Proportional Facultative Reinsurance for Business Interruption and Contingent Business Interruption. ';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-01'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-TOB014-009-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '14' ;                              $OperativeDoc->business_code = '2026-TOB014-009';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save(); 
        $OperativeDoc=new OperativeDoc();          $OperativeDoc->id = '2026-TOB014-010-01';         $OperativeDoc->operative_doc_type_id = '1';        $OperativeDoc->index = '1';         $OperativeDoc->description = 'Proportional Facultative Reinsurance for Business Interruption and Contingent Business Interruption.         ';         $OperativeDoc->inception_date = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->expiration_date = date('Y-m-d',strtotime('2027-02-01'));         $OperativeDoc->document_path =  'reinsurers/business_documents/2026-TOB014-010-01.pdf' ;               $OperativeDoc->af_mf =  '0' ;                                $OperativeDoc->roe_fs =  '1' ;                              $OperativeDoc->created_by_user =  '14' ;                              $OperativeDoc->business_code = '2026-TOB014-010';          $OperativeDoc->created_at = date('Y-m-d',strtotime('2026-02-01'));         $OperativeDoc->updated_at = date('Y-m-d',strtotime(''));         $OperativeDoc->save();          

    }
}