<?php

namespace Database\Seeders;

use App\Models\Business;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessesZamaSeeder2025 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $business=new business();           $business->business_code = '2025-ZMA056-001';          $business->index = '1';             $business->description = 'Facultative Reinsurance – Non-Proportional Automatic Surety Reinsurance Contract (Working Cover).';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Estimated';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '59';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2025-08-01'));           $business->business_lifecycle_status = 'In Force';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2025-08-01'));            $business->source_code = null;             $business->created_by_user =  '16 ' ;              $business->created_at = date('Y-m-d',strtotime('2025-08-01'));   $business->updated_at = date('Y-m-d',strtotime('2025-08-01'));       $business->save(); 
        $business=new business();           $business->business_code = '2025-ZMA056-002';          $business->index = '2';             $business->description = 'Facultative Reinsurance Contract  for Key Man';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '59';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2025-12-01'));           $business->business_lifecycle_status = 'In Force';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2025-12-01'));            $business->source_code = null;             $business->created_by_user =  '16 ' ;              $business->created_at = date('Y-m-d',strtotime('2025-12-01'));   $business->updated_at = date('Y-m-d',strtotime('2025-12-01'));       $business->save(); 
        $business=new business();           $business->business_code = '2025-ZMA056-003';          $business->index = '3';             $business->description = 'Facultative Reinsurance Contract for Directors and Officers Liability';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '59';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2025-12-01'));           $business->business_lifecycle_status = 'In Force';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2025-12-01'));            $business->source_code = null;             $business->created_by_user =  '16 ' ;              $business->created_at = date('Y-m-d',strtotime('2025-12-01'));   $business->updated_at = date('Y-m-d',strtotime('2025-12-01'));       $business->save(); 
        $business=new business();           $business->business_code = '2025-ZMA056-004';          $business->index = '4';             $business->description = 'Facultative Reinsurance Contract  for All Risk';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '59';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2026-01-01'));           $business->business_lifecycle_status = 'Cancelled';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2026-01-01'));            $business->source_code = null;             $business->created_by_user =  '16 ' ;              $business->created_at = date('Y-m-d',strtotime('2026-01-01'));   $business->updated_at = date('Y-m-d',strtotime('2026-01-01'));       $business->save(); 

    }
}