<?php

namespace Database\Seeders;

use App\Models\Business;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BusinessesAdamasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $business=new business();           $business->business_code = '2014-ADA005-001';          $business->Index = '87';             $business->description = 'Facultative Reinsurance Contract';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '7';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2014-12-26'));           $business->business_lifecycle_status = 'Expired';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2014-12-26'));           $business->created_at = date('Y-m-d',strtotime('2014-12-26'));           $business->save(); 
        $business=new business();           $business->business_code = '2014-ADA005-002';          $business->Index = '88';             $business->description = 'Facultative Reinsurance Contract';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '7';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2015-09-09'));           $business->business_lifecycle_status = 'Expired';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2015-09-09'));           $business->created_at = date('Y-m-d',strtotime('2015-09-09'));           $business->save(); 
        $business=new business();           $business->business_code = '2015-ADA005-001';          $business->Index = '89';             $business->description = 'Facultative Reinsurance Contract';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '7';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2015-09-09'));           $business->business_lifecycle_status = 'Expired';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2015-09-09'));           $business->created_at = date('Y-m-d',strtotime('2015-09-09'));           $business->save(); 
        $business=new business();           $business->business_code = '2015-ADA005-002';          $business->Index = '90';             $business->description = 'Facultative Reinsurance Contract';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '7';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2015-12-24'));           $business->business_lifecycle_status = 'Expired';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2015-12-24'));           $business->created_at = date('Y-m-d',strtotime('2015-12-24'));           $business->save(); 
        $business=new business();           $business->business_code = '2015-ADA005-003';          $business->Index = '91';             $business->description = 'Facultative Reinsurance Contract';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '7';                 $business->parent_id = null;             $business->renewed_from_id =  '2014-ADA005-001 ' ;              $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2015-12-24'));           $business->business_lifecycle_status = 'Expired';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2015-12-24'));           $business->created_at = date('Y-m-d',strtotime('2015-12-24'));           $business->save(); 
        $business=new business();           $business->business_code = '2016-ADA005-001';          $business->Index = '92';             $business->description = 'Facultative Reinsurance Contract';         $business->reinsurance_type = 'Facultative';         $business->risk_covered = 'Non-Life';               $business->business_type = 'Own';                $business->premium_type = 'Fixed';               $business->purpose = 'Strategic';                  $business->claims_type = 'Claims occurrence';              $business->reinsurer_id = '7';                 $business->parent_id = null;             $business->renewed_from_id = null;             $business->producer_id = '96';              $business->currency_id = '157';                $business->region_id = '2';              $business->approval_status = 'APR';            $business->approval_status_updated_at= date('Y-m-d',strtotime('2016-03-30'));           $business->business_lifecycle_status = 'Expired';         $business->business_lifecycle_status_updated_at= date('Y-m-d',strtotime('2016-03-30'));           $business->created_at = date('Y-m-d',strtotime('2016-03-30'));           $business->save(); 

    }
}
