<?php

namespace Database\Seeders;

use App\Models\CostNodex;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CostNodesxLogSeeder2025 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251231-0004yFrBexy3tRYNPZJt7ErrVdcExy';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '30 ' ;              $CostNodex->cscheme_id = 'SCHE-20251231-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-31'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-12-31'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251231-0004RbnUNxprnED2PqE3CPnNXNULUa';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.035';         $CostNodex->partner_source_id = '30';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20251231-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-31'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-12-31'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251231-00040fUq71jCrQEESfnbWQcJEnMW3P';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20251231-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-31'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-12-31'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251231-0005xZiadNehT4vDv9xdvA94rzFtke';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '33 ' ;              $CostNodex->cscheme_id = 'SCHE-20251231-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-31'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-12-31'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251231-00054Fim3zdX69wjPwdSxHi5K2H5Yu';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '33';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20251231-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-31'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-12-31'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251231-000510yPHXDXC8m34c1AVkBeVka6ZW';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20251231-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-31'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-12-31'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251231-0006h7WnRqP6h2EDiiCXjAq7wgqmJY';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '25 ' ;              $CostNodex->cscheme_id = 'SCHE-20251231-0006';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-31'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-12-31'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251231-00063QtLMz0rR83tqeHGSVpBPA9kFH';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.035';         $CostNodex->partner_source_id = '25';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20251231-0006';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-31'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-12-31'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251231-0006vUu24J9r8hdtpHjDBWDpdfwEyT';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20251231-0006';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-31'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-12-31'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save();  

    }
}