<?php

namespace Database\Seeders;

use App\Models\CostNodex;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CostNodesxAbatianSeeder2017_2025 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20171228-1401-jpdthmEC5XN1NLMJkkqhw1AgAH';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '59' ;              $CostNodex->cscheme_id = 'SCHE-20171228-1401';       $CostNodex->created_at = date('Y-m-d',strtotime('2017-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20171228-1401-v4F5UmgQdkuVWctX58LPHaSjV9';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.025';         $CostNodex->partner_source_id = '59';        $CostNodex->partner_destination_id =  '50' ;              $CostNodex->cscheme_id = 'SCHE-20171228-1401';       $CostNodex->created_at = date('Y-m-d',strtotime('2017-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20171228-1401-GuXt1tBrFtDixk68CY6n3qXQ1y';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103' ;              $CostNodex->cscheme_id = 'SCHE-20171228-1401';       $CostNodex->created_at = date('Y-m-d',strtotime('2017-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20191228-1402-aLPDK97q8NHG6fi8y1LaGkAyWd';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '59' ;              $CostNodex->cscheme_id = 'SCHE-20191228-1402';       $CostNodex->created_at = date('Y-m-d',strtotime('2019-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20191228-1402-ACnCqvNpmChW1tBpzfeGrEyRim';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '59';        $CostNodex->partner_destination_id =  '50' ;              $CostNodex->cscheme_id = 'SCHE-20191228-1402';       $CostNodex->created_at = date('Y-m-d',strtotime('2019-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20191228-1402-VFGqryN97AipatA7r9vMk81q15';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103' ;              $CostNodex->cscheme_id = 'SCHE-20191228-1402';       $CostNodex->created_at = date('Y-m-d',strtotime('2019-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20231130-1403-YTdFaP0x0JS5uAuk7NrNSe5HFj';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '33' ;              $CostNodex->cscheme_id = 'SCHE-20231130-1403';       $CostNodex->created_at = date('Y-m-d',strtotime('2023-11-30'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20231130-1403-A7MywS0EZSKeDk5MgJ8yyVpFzP';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.026';         $CostNodex->partner_source_id = '33';        $CostNodex->partner_destination_id =  '50' ;              $CostNodex->cscheme_id = 'SCHE-20231130-1403';       $CostNodex->created_at = date('Y-m-d',strtotime('2023-11-30'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20231130-1403-Q9fr09a22HtUT44bfYZZ1NTftM';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103' ;              $CostNodex->cscheme_id = 'SCHE-20231130-1403';       $CostNodex->created_at = date('Y-m-d',strtotime('2023-11-30'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20231228-1404-1Bwfpiy52Q4DG0fUpfENNnpvQF';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '59' ;              $CostNodex->cscheme_id = 'SCHE-20231228-1404';       $CostNodex->created_at = date('Y-m-d',strtotime('2023-11-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20231228-1404-vJJgRwYFptYRP8dZUAQgNunvgJ';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.0325';         $CostNodex->partner_source_id = '59';        $CostNodex->partner_destination_id =  '50' ;              $CostNodex->cscheme_id = 'SCHE-20231228-1404';       $CostNodex->created_at = date('Y-m-d',strtotime('2023-11-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20231228-1404-c4mLGT5JQwVG5ueb05JBxXcqS4';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0175';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103' ;              $CostNodex->cscheme_id = 'SCHE-20231228-1404';       $CostNodex->created_at = date('Y-m-d',strtotime('2023-11-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20241228-1405-LmBnYMGipZnDzn3PkVv68VczNW';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '59' ;              $CostNodex->cscheme_id = 'SCHE-20241228-1405';       $CostNodex->created_at = date('Y-m-d',strtotime('2024-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20241228-1405-07669YzvjJ8mK5AAQin7ZkXiMe';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.0325';         $CostNodex->partner_source_id = '59';        $CostNodex->partner_destination_id =  '50' ;              $CostNodex->cscheme_id = 'SCHE-20241228-1405';       $CostNodex->created_at = date('Y-m-d',strtotime('2024-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20241228-1405-tB6gQS2SWMiXM3NRQ2R5HxpAc1';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103' ;              $CostNodex->cscheme_id = 'SCHE-20241228-1405';       $CostNodex->created_at = date('Y-m-d',strtotime('2024-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251228-1406-jNGF4j4WcWxM8JFizNtZbyFzjw';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '59' ;              $CostNodex->cscheme_id = 'SCHE-20251228-1406';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251228-1406-ZAnfAJ415ZyH5edXPYZxcQzuzZ';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '59';        $CostNodex->partner_destination_id =  '1' ;              $CostNodex->cscheme_id = 'SCHE-20251228-1406';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251228-1406-VT13fxP08b0LtQVLZbhQ469EQe';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.035';         $CostNodex->partner_source_id = '1';        $CostNodex->partner_destination_id =  '103' ;              $CostNodex->cscheme_id = 'SCHE-20251228-1406';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251228-1407-QFDWzTKdrqBAAHn5iM3LGNMbeA';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '33' ;              $CostNodex->cscheme_id = 'SCHE-20251228-1407';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251228-1407-C6tpNWbSjxQp7HEg5rmVgwH7L8';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.026';         $CostNodex->partner_source_id = '33';        $CostNodex->partner_destination_id =  '1' ;              $CostNodex->cscheme_id = 'SCHE-20251228-1407';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251228-1407-UvRhJumCcU9jXNruWTQxWqyk5T';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.035';         $CostNodex->partner_source_id = '1';        $CostNodex->partner_destination_id =  '103' ;              $CostNodex->cscheme_id = 'SCHE-20251228-1407';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251228-1408-YnFanvWT9nKDcpCaPj6nTTuzfd';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '59' ;              $CostNodex->cscheme_id = 'SCHE-20251228-1408';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251228-1408-70fNTAgKvZvBA4gDiS8GnnEU1B';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.0325';         $CostNodex->partner_source_id = '59';        $CostNodex->partner_destination_id =  '1' ;              $CostNodex->cscheme_id = 'SCHE-20251228-1408';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251228-1408-VFphjKJ9jqPgndzLfgZ9mk3zRp';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.035';         $CostNodex->partner_source_id = '1';        $CostNodex->partner_destination_id =  '103' ;              $CostNodex->cscheme_id = 'SCHE-20251228-1408';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-12-28'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-04-13'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save();   
    }
}
