<?php

namespace Database\Seeders;

use App\Models\CostNodex;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CostNodesxHorusSeeder2025 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250601-0001XG7NWkMq3D0n2CKEk8674Q74WP';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '28 ' ;              $CostNodex->cscheme_id = 'SCHE-20250601-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-06-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-06-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250601-0001qLvfnqceBtayQc51Y7LgLgg7Ub';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '28';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20250601-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-06-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-06-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250601-0001F3wDxYNmByuhBxRzdpXwZyeet3';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.025';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250601-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-06-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-06-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250801-0002zduZTzvqrrqqnL0thWAQHGMM0c';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '28 ' ;              $CostNodex->cscheme_id = 'SCHE-20250801-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-08-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-08-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250801-0002w8WgUPeNdMfaRD7jUAK1nycdrf';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '28';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20250801-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-08-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-08-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250801-0002GxNanrz4ZLGeS6r15KH1RLYGcu';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.025';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250801-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-08-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-08-01'));     $CostNodex->apply_to_gross = 'TRUE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250801-0001v9Y4Ep1649TSyCmPVvxBd7CwYb';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '28 ' ;              $CostNodex->cscheme_id = 'SCHE-20250801-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-08-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-08-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250801-0001Wqg9BXZAMGqdHn4XLaC5E0wq3S';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '28';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20250801-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-08-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-08-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250801-0001nfZ1Rx4cANt2KtxkHh71FAbP6K';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250801-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-08-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-08-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250801-0003Wxt1Mn96Rm3w5epUeumwq9tbuZ';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '64 ' ;              $CostNodex->cscheme_id = 'SCHE-20250801-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-08-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-08-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250801-0003iipyqQ1EJwHmvRYNTEnB7XW3m2';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '64';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20250801-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-08-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-08-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250801-0003GrSWuw7b0M7tEMVHbccUWL8er7';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250801-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-08-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-08-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0001KTvFAYfK9aQyqF69FcaXrk8jVt';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '64 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0001qKpiqN7MQLwhn1veUq3w0zVybA';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '64';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0001cQ6UXJGW1Yj6j00wr7mZDtL2Cg';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0175';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0002GzKQDax5G2eXx4AJGD7tQwDcaV';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '28 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-00029ZKm5M56VSM4g7qDetdD6Li99t';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '28';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0002u0v2y3qn5QN0BQmMZdhDJqghwR';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0175';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0003cCVKhzh2iGLiYLcuqJKTmy7aKt';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '64 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-00032VQv5eTd1TW5Vr2wTj6NnUz7fq';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '64';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0003B5YhE8ZGkZVyH5FcJC5nEGuuAa';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0225';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0004yUYK88Nk2dJmRzi5qVVemTLQK4';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '28 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0004B0PqqTnZM4jzVa93YtS8HLqCjV';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '28';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0004nNhce8QYwW9yp2kHdhFF9nYSaH';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0225';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0005jjb0Dzewxv8Yrhki1TJfgDmKKL';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '25 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0005V1gftUqEiDQQLxBEQFLAtHigWK';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '25';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0005Fp1dMiWZL2P9vrJeWectT8zYNa';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0175';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-11-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-11-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20260101-0006tTZ6KwBB2FRqCPcM4GD43hWybf';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '64 ' ;              $CostNodex->cscheme_id = 'SCHE-20260101-0006';       $CostNodex->created_at = date('Y-m-d',strtotime('2026-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20260101-0006Uz9NcE3Kh6knrWmNT3HmkSMREp';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '64';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20260101-0006';       $CostNodex->created_at = date('Y-m-d',strtotime('2026-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20260101-0006J7KHWULA8UGABqcbyME9XbrLD6';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0225';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20260101-0006';       $CostNodex->created_at = date('Y-m-d',strtotime('2026-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0007DRqYrzyt40nQH5Mbi6eKuh3ED2';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '28 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0007';       $CostNodex->created_at = date('Y-m-d',strtotime('2026-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0007CdH7PEXTrAQXXE8qvANZTm1ydU';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '28';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0007';       $CostNodex->created_at = date('Y-m-d',strtotime('2026-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20251101-0007NKkyuU07uuGpwGpf6iLNyC22wE';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0225';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20251101-0007';       $CostNodex->created_at = date('Y-m-d',strtotime('2026-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2026-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save();     

    }
}