<?php

namespace Database\Seeders;

use App\Models\CostNodex;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CostNodesxPapillonSeeder2025 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-00013rzwYuUSpt0tHSE5VPtqjc3080';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '47 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0001D2nP86zL2jp9kvxPH4NpJp2NTG';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.08970165';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0001MLdb4zcn2vBBe6ZBhKpNG5cqcG';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.06323766';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0002rbcJkGuWEkd8Ckh4AxrGjeYLe6';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '47 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0002pf1G7dMGry3frB0pX5x0drF7H5';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.07969905';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0002RDzVUCyQRCwBedcDicCuBb4Vqh';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.0628769';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0003HgQTuTJf79D5Ta1EWXuR6Hm5YC';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '47 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0003dLgWEQzg9cqr1NxgD2C1y3n32X';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.11469809';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-00037WTbpcGFS1dV72MnZDQi7hiZ4T';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.06499908';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0004g6Q3BAMicBermRDb6dhFkC08zj';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '47 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0004Ug57iM3EuNw9ajbPnWTR8RZZGD';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.08969596';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0004FkTx8yYch4jzW9iYArkf7pf9pq';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.01689684';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0005HZ3k8AfnUzrHGB7kXE2ntuVuQf';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '47 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0005Raqndgy6CqULUk6t3jAH1vk5LH';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.09219203';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-000551Fh2MKKQeMwJqcmbZA9JyNhxy';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.06998041';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0006A21jEFKLFAvUVdmKxFt0LdEeTa';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '47 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0006';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0006g69nkdV2g7rnNULtjxyHxGqfbA';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.0897032';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0006';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0006QnrbqUiZ4REvwpCZVXqDiGr4ux';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.07000034';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0006';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0007zbma5CEVf0uxjdh7Lf5780mQ0k';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '47 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0007';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0007e0f0xjh99ypeBiczptebyVQYpr';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.08970038';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0007';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0007w2UrP0vHv6KRMFyBAR9JAH8Vjh';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.03490377';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0007';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0008uJ0weiPKchd14EB08rNqwadeaH';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '47 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0008';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0008AAnv9MKmMJqC8D1heBX8FyaEgB';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.08970154';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0008';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0008q3KjXWXLy4gCME0uRxDAfEHb4u';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.03499322';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0008';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-00099wPajFJqB6AUP3Cpy6gLXj5huj';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '47 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0009';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-00097GwuUc0wydwzQqMe3pppzLRX5T';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.11222731';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0009';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0009dgGPxbb8iMJ9ukzHDXQLNT2Uyx';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.06962066';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0009';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0010EtiCmKvPGx3B2CGJejRKkvqGgq';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '47 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0010';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0010rvAwitgrSzAHcPSQf9przaaruM';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.1146981';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '1 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0010';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0010rkv2E2f09eT9XSQurB4FB9xyUK';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.06499826';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '1 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0010';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-00118F0Zqa9vp0WYvQ3Xj0hXDqF1JY';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '47 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0011';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0011kedk07dNyUp1hbDzeerMXWGR53';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.08969769';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0011';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0011cMp8BpZ3BZf8UqLNkXWWAK1JTJ';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.03499317';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0011';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0012F03zw7YCtLiM3vAQekzibEwp2P';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '47 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0012';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-0012CYUdeY4k1UpvHS6Q4E5gdqrwyh';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.08967697';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0012';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250127-00122NiefX9feZJZK7Y8hpqYK99bSZ';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.03229502';         $CostNodex->partner_source_id = '47';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250127-0012';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250203-00015gAhuLz8WZPrzSYvmcFv3uB2kV';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '4 ' ;              $CostNodex->cscheme_id = 'SCHE-20250203-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250203-0001gRA0CrUm7C0dVLJGHE3hm93jAA';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.086212221';         $CostNodex->partner_source_id = '4';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250203-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0001JjwzMZ10gfgFxickdUumy0D7Mi';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '87 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0001yixTvY7PbZD4ShzXgHwaYuDd3C';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.01';         $CostNodex->partner_source_id = '87';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0001bHKDhF4tLAemcUvENWcvtTfmrH';       $CostNodex->index = '4';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0001n4GCBaDJUJKWkZpPYDCnXAktR0';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '87';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'TRUE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0002vzD0mak14diEC9EjTkXmPHnERE';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '26 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0002jJvBFepPv8MZhPmHWCY73dJXAH';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '26';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0002DkM7CGNWX5faBtRebvAzGNVwYD';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0003JrZrhTAHhfDJA8H28e3AKgPtSB';       $CostNodex->index = '5';        $CostNodex->concept = '1';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '54';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'TRUE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0003xY0qyejy0kXwa2Hm8LgC9zxZKx';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '119 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0003ZHBz6Yn9J4AGaDMHYRJRamrTT5';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '119';        $CostNodex->partner_destination_id =  '54 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0003R5h24WZQP4waZBbnrFx1834QWe';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.003';         $CostNodex->partner_source_id = '119';        $CostNodex->partner_destination_id =  '54 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0003i1K6wRZDwz8i27PkXQCk6Jrf4V';       $CostNodex->index = '4';        $CostNodex->concept = '4';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '119';        $CostNodex->partner_destination_id =  '54 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'TRUE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250204-0003pbuKEcgwVJrmvhT73HLTmUx83h';       $CostNodex->index = '6';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250204-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250205-0004v2fPMxHybD03Zay4bPc7qTvdSP';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '3 ' ;              $CostNodex->cscheme_id = 'SCHE-20250205-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250205-0004Na0b7ehESbTeuJUvCRYXV16tVq';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.080850947';         $CostNodex->partner_source_id = '3';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250205-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-0001G9iSMVEcYSngMRrKkpefVFFndV';       $CostNodex->index = '2';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '119 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-0001GZTPPLTq82RvTPH9Kw7hiDu9yF';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '119';        $CostNodex->partner_destination_id =  '54 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-0001UgzJE3NHawDNqSp2ur6YNLTp7K';       $CostNodex->index = '4';        $CostNodex->concept = '4';        $CostNodex->value = '0.003';         $CostNodex->partner_source_id = '119';        $CostNodex->partner_destination_id =  '54 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-0001pbBJjweqeyHxZjtdrxTJ3paTbe';       $CostNodex->index = '1';        $CostNodex->concept = '4';        $CostNodex->value = '0.04735';         $CostNodex->partner_source_id = '119';        $CostNodex->partner_destination_id =  '54 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-0001PHPR9EeYkjv5g6vWCJpPHGawa5';       $CostNodex->index = '5';        $CostNodex->concept = '1';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '54';        $CostNodex->partner_destination_id =  '23 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-0001nGfdKKT4HxhtAJMWqdt9JJhdPx';       $CostNodex->index = '6';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '23';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-00023bq12fNZprPNydA8z8QfJ1PWqR';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '87 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-0002Dz0SnPYkQPZPm6TPXUkYaeyMBw';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.01';         $CostNodex->partner_source_id = '87';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-0002YwabKCAXUx6FrtpAQhFCp84vFV';       $CostNodex->index = '4';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-0002fXqi8QyU3bniARxx6LipKDKbyL';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.0495';         $CostNodex->partner_source_id = '87';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-0003eTyNL3Eny8iUPJyuyReE2yHZR4';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '26 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-0003cXX6Gn7xLhbLnkx8YBGw3q4x8z';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '26';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250206-0003Fv3rvH8LNfC92T1b7gY3XTS8FA';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250206-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250209-0012gTgrt2zc3QWdXVahG4uCDL6wew';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '87 ' ;              $CostNodex->cscheme_id = 'SCHE-20250209-0012';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250209-0012C9NhV0WMTQ5P2xGBDa9bxEAUMk';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.01';         $CostNodex->partner_source_id = '87';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250209-0012';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'TRUE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250209-0012z4VEQWrXTKathv5hHUjq03Rgnb';       $CostNodex->index = '4';        $CostNodex->concept = '4';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '87';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250209-0012';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'TRUE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250209-0012yz54fZXKZWnZYKuGjuWRCAhK3W';       $CostNodex->index = '5';        $CostNodex->concept = '1';        $CostNodex->value = '0.0225';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250209-0012';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'TRUE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250209-0012F1JUruAu16ZeXazRQtF6yu02Tb';       $CostNodex->index = '2';        $CostNodex->concept = '4';        $CostNodex->value = '0.15';         $CostNodex->partner_source_id = '87';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250209-0012';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0001WYvJTM5K10yS092jwZTt9ZrdT9';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '156 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0001hPzUDmPmFnv9SERuFKVqUN41f8';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '156';        $CostNodex->partner_destination_id =  '13 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-00018LwRzzgw9yu0yBVc4FXjERk74j';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '156';        $CostNodex->partner_destination_id =  '13 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0001qCmx71P1x8hxyhYmgTEybjqZD6';       $CostNodex->index = '4';        $CostNodex->concept = '7';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '156';        $CostNodex->partner_destination_id =  '13 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0001LKmSjQuwKuMCtaUFUR7iNKgg8W';       $CostNodex->index = '5';        $CostNodex->concept = '1';        $CostNodex->value = '0.026075';         $CostNodex->partner_source_id = '13';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0002ynFWxj0nwc3DH0S8kBezt2N12q';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '157 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-00028UudwKLB1L0Q7vx0tf67a3A9Lu';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.0441';         $CostNodex->partner_source_id = '157';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0003Ra3DacW8J8DM8cVKpiKw4NS5fA';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '26 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0003S5F21V7eZG4Mj0F6MAwDYJCWJu';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '26';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0003Qa0Adc8JfE7JmipmeJWHuKPmRx';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '26';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0003XwQpdm1xg9k9jN9wUb1Bewv7hZ';       $CostNodex->index = '4';        $CostNodex->concept = '1';        $CostNodex->value = '0.0225';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0004bhCz0BhgS616PDfZafv82KjkTx';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '26 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0004w3c7feRFdewiR265FXP4EMnyN6';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '26';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0004i838yGqzny8JXxPY10i3nfFcJq';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0225';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-00058LgfShWNYHzf0y2Xiz491mqmXm';       $CostNodex->index = '5';        $CostNodex->concept = '1';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '54';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'TRUE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0005ACB5i2L5r0ZTUNWjA29GB22wKR';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.003';         $CostNodex->partner_source_id = '119';        $CostNodex->partner_destination_id =  '54 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0005MMdaADqJ3GpNXrUAzAFU864xbH';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '119 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-00053rpSGJfq9R3A7LQdDBuQ3xeMS8';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '119';        $CostNodex->partner_destination_id =  '54 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0005RGSLA5AzkazqFkZhquD0eBQJZk';       $CostNodex->index = '4';        $CostNodex->concept = '4';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '119';        $CostNodex->partner_destination_id =  '54 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'TRUE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250210-0005ptuNxEuchRyTgNAzCrBcBf09wy';       $CostNodex->index = '6';        $CostNodex->concept = '1';        $CostNodex->value = '0.0225';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250210-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0001rQ3mW4n62zj8Fjr73HNL8kyT31';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '157 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0001XrVFpnbXtJSHtj2JH5XYBW5ff4';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.03';         $CostNodex->partner_source_id = '157';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0002yWiUn8NzQMteKX6JKPZEB4VYb0';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '156 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0002m7f1VP8kgAJw7AxyZ9MTrAwNHV';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '156';        $CostNodex->partner_destination_id =  '13 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0002Kg5Uv4qAr3JvWDRpwJnYLrbyHB';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '156';        $CostNodex->partner_destination_id =  '13 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0002UMg0rkz1KFgRD1tfgh8h2DZvNx';       $CostNodex->index = '4';        $CostNodex->concept = '4';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '156';        $CostNodex->partner_destination_id =  '13 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-00028k84PwvGEpSZQtDD2gpwBgpDhv';       $CostNodex->index = '5';        $CostNodex->concept = '1';        $CostNodex->value = '0.026075';         $CostNodex->partner_source_id = '13';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-000380p7Eu3rxDACSUxut1h3wnHLRw';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '4 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0003k9LkR8L2ZJixpbJ6j1cRYVBRRe';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.086212221';         $CostNodex->partner_source_id = '4';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0003VUBebu8beCrV0Ypp1SjKb0d39x';       $CostNodex->index = '2';        $CostNodex->concept = '4';        $CostNodex->value = '0.1';         $CostNodex->partner_source_id = '4';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0004Neh7aYShmd81z4W9mu9tUUNDKW';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '4 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0004DenTqVaK8EeM9dYYa64ZN0CZMV';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.05';         $CostNodex->partner_source_id = '4';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0004YhevhhN1t5dYzHkLiS6uqhb9ih';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.086212221';         $CostNodex->partner_source_id = '4';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0005t4gGv54Q3zpXWM0RB7bTzkKe2W';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '4 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-00056BEE43xRpBjgANuGJMQmHXM7iw';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.086212221';         $CostNodex->partner_source_id = '4';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250211-0005ZyiC3A1Hb3dj7TPHKr9G0f7j9j';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '4';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250211-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250225-0001jeAMX5RpZ6LCChgfZnzF995pSD';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '78 ' ;              $CostNodex->cscheme_id = 'SCHE-20250225-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250225-0001xZNGRYtWKLKKyqT2zm8v4jNpN2';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.01';         $CostNodex->partner_source_id = '78';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250225-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250225-00018QTRAxJBejeYee1d3VCj5jtABa';       $CostNodex->index = '4';        $CostNodex->concept = '1';        $CostNodex->value = '0.0225';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250225-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250225-0001FKVZwSVexnNyjEMRJwn3V3w0am';       $CostNodex->index = '3';        $CostNodex->concept = '4';        $CostNodex->value = '0.0495';         $CostNodex->partner_source_id = '78';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250225-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250225-0002KQD5Y7FkiCxYLRkkBHGiDbtuyR';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '26 ' ;              $CostNodex->cscheme_id = 'SCHE-20250225-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250225-0002WtXut9fCq9t64gqe4QV4g6FcGF';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '26';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250225-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250225-0002uBFRCP5PDiGa7YkYFPB6nVdTch';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0225';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250225-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 

    }
}