<?php

namespace Database\Seeders;

use App\Models\CostNodex;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CostNodesxOmegaSeeder2025 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0001Cv901LC527fzb18figSzQkMtTY';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '30 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0001NTXx7FPgidEDNAViXp70AC19Af';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.035';         $CostNodex->partner_source_id = '30';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0001A5rhTCJ9gznMTCvvDqYLHkS2PE';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.025';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0001';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0002BLKMpx5Dv1yVwFgvm9qLKCbVqu';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '25 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0002fDtE3p8W3Rh5rdA1wfT5VMuagd';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.045';         $CostNodex->partner_source_id = '25';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0002XxyGSZLRLF2SfKvryrUyvhTHAP';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0002';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0003CtVeUdQHAYPf5Hq5yBCDzGkhZ9';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '30 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0003G7pLiQCNz4wGGjtPHKwfr2NFUL';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.045';         $CostNodex->partner_source_id = '30';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0003dPF0R4YriqqAnMpNKYkM6aAvg8';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0003';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0004kMkiYCby6kT5yNCMGy9DLXJUyd';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '25 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0004TuEEv3RdHM9bvMNUPheGhW6ZRi';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.045';         $CostNodex->partner_source_id = '25';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0004iE99UxLgBZQrQhE1PM53VBKBfM';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.025';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0004';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0005RYvL4xzZruima4fCGX1r65TSXk';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '30 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0005t6ETUGkCycCy9jb57xxeY6jgBr';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.035';         $CostNodex->partner_source_id = '30';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-00050JRqQLKkhgznvUVvk7aB6VuyLx';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.02';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0005';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0006r3ytPtY0BJdJuvd4YMPcvi17NC';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '25 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0006';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0006M83nt35ScYcGPRZxu9EdUByRTU';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.035';         $CostNodex->partner_source_id = '25';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0006';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0006mqyHgHgf5WyZSz8nbTSm8X2JR8';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.025';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0006';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0007ye5iRzvmdrSFt9rQGC1baFEvGu';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '30 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0007';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0007VbWYD60JMmgmFzBPL1eQBE5K4W';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.035';         $CostNodex->partner_source_id = '30';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0007';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0007A9X7muULPfrmcAMeXtU9Lc4eHT';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0175';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0007';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0008ELVMF5y9ia7piEXXvDny89bTBW';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '33 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0008';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0008Rnc9pShVuNqRKfc6fKBqp82PcA';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.025';         $CostNodex->partner_source_id = '33';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0008';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0008GMX9HyCuZizz3x6KLM6Sp4c5Yj';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0175';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0008';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0009LVY0UGKGdntuV2YpccBKB2BH0P';       $CostNodex->index = '1';        $CostNodex->concept = '8';        $CostNodex->value = '0';         $CostNodex->partner_source_id = '94';        $CostNodex->partner_destination_id =  '64 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0009';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-000928Pr44zD242FDwrF0PV50X6n1w';       $CostNodex->index = '2';        $CostNodex->concept = '1';        $CostNodex->value = '0.0325';         $CostNodex->partner_source_id = '64';        $CostNodex->partner_destination_id =  '50 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0009';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save(); 
        $CostNodex=new CostNodex();          $CostNodex->id = 'SCHE-20250323-0009kW3k9unrtL6ft2i0WdNG3k47VP';       $CostNodex->index = '3';        $CostNodex->concept = '1';        $CostNodex->value = '0.0175';         $CostNodex->partner_source_id = '50';        $CostNodex->partner_destination_id =  '103 ' ;              $CostNodex->cscheme_id = 'SCHE-20250323-0009';       $CostNodex->created_at = date('Y-m-d',strtotime('2025-01-01'));         $CostNodex->updated_at = date('Y-m-d',strtotime('2025-01-01'));     $CostNodex->apply_to_gross = 'FALSE';      $CostNodex->save();           

    }
}