<?php

namespace Database\Seeders;

use App\Models\CostNode;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CostNodesCellMayabSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        
        $CostNode=new CostNode();          $CostNode->id = 'd0becf19-fcbb-4ebf-8bae-fcd16737f9f0';         $CostNode->concept = '1';        $CostNode->value = '0.024';         $CostNode->partner_id = '67';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '826dfce8-2440-436d-a11b-3f501c2997cf';         $CostNode->concept = '1';        $CostNode->value = '0.0239575701848997';         $CostNode->partner_id = '67';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '9c4355b7-dd52-4fa6-b948-3621cd7f0df6';         $CostNode->concept = '1';        $CostNode->value = '0';         $CostNode->partner_id = '67';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '54331146-c241-40c4-a4d1-b61db87cfa19';         $CostNode->concept = '1';        $CostNode->value = '0.0268928354124857';         $CostNode->partner_id = '67';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'fe5f222e-5d67-46f1-a60a-492a0aa9384e';         $CostNode->concept = '1';        $CostNode->value = '0.02689';         $CostNode->partner_id = '67';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '8908dfeb-6f37-4358-b737-ee52cb50588c';         $CostNode->concept = '1';        $CostNode->value = '0.0201';         $CostNode->partner_id = '67';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '9af70e36-2826-43d8-89f0-6b4dd45d053e';         $CostNode->concept = '1';        $CostNode->value = '0.023077';         $CostNode->partner_id = '67';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'e4303a6a-78b8-49ac-b3ef-f7937a549432';         $CostNode->concept = '1';        $CostNode->value = '0.02';         $CostNode->partner_id = '67';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '5d0296ee-5efc-423f-987c-11fd96574440';         $CostNode->concept = '1';        $CostNode->value = '0.02';         $CostNode->partner_id = '59';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'd2ff41dd-9b88-474c-a941-93ae4d231d41';         $CostNode->concept = '1';        $CostNode->value = '0.0075';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '006d59e0-ce84-45b2-a286-70667cceb3a6';         $CostNode->concept = '1';        $CostNode->value = '0.0075';         $CostNode->partner_id = '55';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '56ea9e1e-1140-4d4b-b545-af69cf1b4e59';         $CostNode->concept = '1';        $CostNode->value = '0.0100487991639367';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '606200f2-8dfb-4266-8cf7-5f56d331b90e';         $CostNode->concept = '1';        $CostNode->value = '0.0119787850924499';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'bde87825-0e63-44d1-be2d-876cc1b6e524';         $CostNode->concept = '1';        $CostNode->value = '0';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '2dc5331f-83dd-46fb-98a0-bd1d95c61d38';         $CostNode->concept = '1';        $CostNode->value = '0.012';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'b7e3ce14-eea5-42c1-bb69-84d61a21c916';         $CostNode->concept = '1';        $CostNode->value = '0.0125';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'f93e4b43-efaa-462b-99b2-659550b5962d';         $CostNode->concept = '1';        $CostNode->value = '0.0125';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '45660fea-0f4a-4eb5-8874-3def747a32f4';         $CostNode->concept = '1';        $CostNode->value = '0.012501274';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'b937085e-e4ac-4442-877d-aacc865d4c53';         $CostNode->concept = '1';        $CostNode->value = '0.013462';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '8b486d49-d6d8-4f82-9e24-bccc594a870f';         $CostNode->concept = '1';        $CostNode->value = '0.0149';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'd8c4737c-860a-43a3-9005-fca5bc45ebfd';         $CostNode->concept = '1';        $CostNode->value = '0.015';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'd0965203-bf99-4234-945e-9db4128ad82b';         $CostNode->concept = '1';        $CostNode->value = '0.022185';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '44b09b9d-83fb-4d45-93e9-31c18a8a382a';         $CostNode->concept = '1';        $CostNode->value = '0.0221865892153007';         $CostNode->partner_id = '80';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '4981332d-00fa-4c68-9659-ce8c18569cff';         $CostNode->concept = '1';        $CostNode->value = '0.00551250058014657';         $CostNode->partner_id = '1';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'e41b595d-452b-4800-bf01-85651b281b84';         $CostNode->concept = '3';        $CostNode->value = '0.0178571427960188';         $CostNode->partner_id = '13';        $CostNode->referral_partner =  'Gatekeeper ' ;              $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '19851749-1e4b-4e55-ac9a-a928a0c0c6cc';         $CostNode->concept = '1';        $CostNode->value = '0.0175';         $CostNode->partner_id = '13';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '243b105d-8c3e-4b13-8dce-160e1caf66e0';         $CostNode->concept = '1';        $CostNode->value = '0.0175';         $CostNode->partner_id = '13';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '984f73bb-4198-43e6-80ec-6e5a1652c08f';         $CostNode->concept = '1';        $CostNode->value = '0.00551250058014657';         $CostNode->partner_id = '13';        $CostNode->referral_partner =  'Gatekeeper ' ;              $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '17d05e2a-b41b-42fe-9a90-3f872911b49c';         $CostNode->concept = '3';        $CostNode->value = '0.00337500198516609';         $CostNode->partner_id = '1';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '818e6394-a410-440d-b8bd-3b9943de8b26';         $CostNode->concept = '1';        $CostNode->value = '0.02';         $CostNode->partner_id = '50';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '616fe183-1fc0-470a-abf7-87b19cdb5bad';         $CostNode->concept = '1';        $CostNode->value = '0.025';         $CostNode->partner_id = '40';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '9b827aee-b863-4fea-bb15-b3e27d07ecff';         $CostNode->concept = '1';        $CostNode->value = '0.025002548';         $CostNode->partner_id = '40';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '6691cec3-60e8-41b9-97fd-4211fa370bd7';         $CostNode->concept = '1';        $CostNode->value = '0.0262';         $CostNode->partner_id = '40';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '949588e2-3e02-4756-ba6b-f3ec102fbbaf';         $CostNode->concept = '1';        $CostNode->value = '0.025';         $CostNode->partner_id = '11';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '7ddca113-d8e4-4f4b-8d0f-222d8c26be9e';         $CostNode->concept = '1';        $CostNode->value = '0.0262';         $CostNode->partner_id = '11';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'db201552-4082-4726-a6be-04826ad63c4a';         $CostNode->concept = '1';        $CostNode->value = '0.0263';         $CostNode->partner_id = '11';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'df3158f3-5f01-43b4-9330-fe5fe2197766';         $CostNode->concept = '1';        $CostNode->value = '0.0271318608437004';         $CostNode->partner_id = '11';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '0ce88a3a-9541-4973-8d21-1ce63b2607d0';         $CostNode->concept = '1';        $CostNode->value = '0.0323427197496146';         $CostNode->partner_id = '11';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = 'ad5ce75b-2a0c-435e-b07a-65f1feb6e823';         $CostNode->concept = '1';        $CostNode->value = '0';         $CostNode->partner_id = '11';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '1e5aae4c-7aa1-44f3-b6a5-d06f5aea825d';         $CostNode->concept = '1';        $CostNode->value = '0.033615';         $CostNode->partner_id = '11';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save(); 
        $CostNode=new CostNode();          $CostNode->id = '929e7b23-47fe-40a9-9ae9-0723fc621dd4';         $CostNode->concept = '1';        $CostNode->value = '0.0336160442656071';         $CostNode->partner_id = '11';        $CostNode->referral_partner = null;             $CostNode->reinsurer_id = '3';         $CostNode->save();    



        
    }
}
