<?php

namespace Database\Seeders;

use App\Models\coverage;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CoveragesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $coverage=new coverage();       $coverage->name = 'Admin & Legal Bond';        $coverage->acronym = 'ALB';         $coverage->description = 'Coverage that ensures compliance with legal and administrative obligations.';        $coverage->lob_id = '4';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Administrative, Supplier and Compliance';        $coverage->acronym = 'ASC';         $coverage->description = 'Protection against risks associated with administrative duties and supplier compliance.';        $coverage->lob_id = '4';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Agriculture';        $coverage->acronym = 'AGR';         $coverage->description = 'Insurance for crops, livestock, and farm property against various risks.';        $coverage->lob_id = '1';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'All Risk';        $coverage->acronym = 'ARSK';         $coverage->description = 'Comprehensive coverage against a wide range of perils, except those explicitly excluded.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Appliances Extended Warranty';        $coverage->acronym = 'AEW';         $coverage->description = "Extended protection for household appliances beyond the manufacturer's warranty.";        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Bankers Blanket Bond';        $coverage->acronym = 'BBB';         $coverage->description = 'Provides financial institutions with coverage against losses arising from dishonest or fraudulent acts by employees, theft, forgery, cyber fraud, and other criminal activities that affect the bank’s assets.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Boilers and Pressure Vessels';        $coverage->acronym = 'BPV';         $coverage->description = 'Coverage for damage to boilers and pressure vessels and liability for any accidents caused.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Buildings and Contents';        $coverage->acronym = 'BCT';         $coverage->description = 'Insurance for the structure of buildings and the contents within against various risks.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Business Interruption';        $coverage->acronym = 'BINT';         $coverage->description = 'Compensation for lost income and expenses due to a disruption in business operations.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Car Cargo';        $coverage->acronym = 'CGO';         $coverage->description = 'Protection for goods transported by car against damage or loss.';        $coverage->lob_id = '3';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Car Extended Warranty';        $coverage->acronym = 'CEW';         $coverage->description = 'Extended coverage for car repairs beyond the manufacturer‚Äôs warranty period.';        $coverage->lob_id = '3';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Car Insurance';        $coverage->acronym = 'CI';         $coverage->description = 'General term for coverage against damages and liabilities related to car ownership and use.';        $coverage->lob_id = '3';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Car Physical Damage';        $coverage->acronym = 'CPD';         $coverage->description = 'Insurance specifically for damage to the vehicle itself.';        $coverage->lob_id = '3';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Car Theft';        $coverage->acronym = 'CTHF';         $coverage->description = 'Coverage against the theft of a car.';        $coverage->lob_id = '3';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Car Third Party Liability';        $coverage->acronym = 'CTPL';         $coverage->description = "Insurance covering liabilities to third parties for bodily injury or property damage caused by the insured vehicle.";        $coverage->lob_id = '3';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Care, Custody or Control Liability';        $coverage->acronym = 'CCC';         $coverage->description = "Protection against liabilities arising from damage to property under the insured's care, custody, or control.";        $coverage->lob_id = '5';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Cash & Values';        $coverage->acronym = 'CVAL';         $coverage->description = 'Insurance for cash and valuable items against theft or damage.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Casualty';        $coverage->acronym = 'CTY';         $coverage->description = 'General liability insurance covering accidents resulting in bodily injury or property damage.';        $coverage->lob_id = '5';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Catastrophic';        $coverage->acronym = 'CIC';         $coverage->description = 'Coverage for large-scale, severe events causing significant damage and loss.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Company Reimbursement';        $coverage->acronym = 'CRB';         $coverage->description = 'Reimburses the Company for Loss it pays on behalf of Directors and Officers, to the extent that such indemnification is legally permissible and actually made by the Company.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Compliance, Advance Payment and Hidden Vices';        $coverage->acronym = 'CAPHV';         $coverage->description = 'Insurance addressing risks related to compliance, prepayments, and hidden defects.';        $coverage->lob_id = '4';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Comprehensive General Liability';        $coverage->acronym = 'CGL';         $coverage->description = 'Broad liability insurance covering various risks including bodily injury, property damage, and personal injury.';        $coverage->lob_id = '6';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Consequential Loss';        $coverage->acronym = 'CLOS';         $coverage->description = 'Coverage for financial losses resulting indirectly from an insured event.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Contingent Business Interruption';        $coverage->acronym = 'CBI';         $coverage->description = "Protection against income loss due to disruptions at a supplier's or customer's location.";        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Contract Cancellation';        $coverage->acronym = 'CCAN';         $coverage->description = 'Coverage for financial losses due to the cancellation of a contract.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Contractors Plant & Equipment';        $coverage->acronym = 'CPE';         $coverage->description = 'Insurance for construction equipment and machinery against damage or loss.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Crime';        $coverage->acronym = 'CRIME';         $coverage->description = 'Coverage against losses resulting from criminal acts such as theft, fraud, and embezzlement.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Cyber';        $coverage->acronym = 'CYBER';         $coverage->description = 'Protection against risks associated with cyber attacks and data breaches.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Debt Insurance';        $coverage->acronym = 'DBI';         $coverage->description = 'Coverage to ensure repayment of loans and debts in case of certain events.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Debtors';        $coverage->acronym = 'DEBT';         $coverage->description = 'Insurance protecting businesses against non-payment by customers.';        $coverage->lob_id = '9';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Deductible Buy Back';        $coverage->acronym = 'DBB';         $coverage->description = 'Insurance to cover the deductible amount in another policy.';        $coverage->lob_id = '11';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Delay in Start-Up';        $coverage->acronym = 'DSU';         $coverage->description = 'Coverage for financial losses due to delays in project commencement.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Difference in Conditions';        $coverage->acronym = 'DINC';         $coverage->description = 'Supplemental insurance covering perils not included in standard policies.';        $coverage->lob_id = '11';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Directors and Officers Liability';        $coverage->acronym = 'D&O';         $coverage->description = 'Protection for company directors and officers against personal liability for actions taken in their corporate roles.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Earthquake Parametric';        $coverage->acronym = 'EPAR';         $coverage->description = 'A coverage that automatically triggers payment to the insured when a predefined seismic threshold is exceeded, such as a specific earthquake magnitude or ground shaking intensity, regardless of physical damage.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Electronic Equipment';        $coverage->acronym = 'ELEQ';         $coverage->description = 'Coverage for damage or loss of electronic devices and systems.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Energy';        $coverage->acronym = 'ENRG';         $coverage->description = 'Insurance for risks associated with energy production and distribution.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Entity Coverage (Securities Claims)';        $coverage->acronym = 'ECSC';         $coverage->description = 'Provides direct coverage to the Company for Loss arising from Securities Claims made against it, applicable when the Insured Entity is publicly traded.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Erection All Risk';        $coverage->acronym = 'EAR';         $coverage->description = 'Coverage for risks associated with the construction and erection of buildings and structures.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Extended Warranty';        $coverage->acronym = 'EXTWAR';         $coverage->description = "Prolonged coverage for products beyond the manufacturer's warranty period.";        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Extraordinary Expenses';        $coverage->acronym = 'EXTEXP';         $coverage->description = 'Insurance for unexpected and significant expenses arising from insured events.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Familiar';        $coverage->acronym = 'FAM';         $coverage->description = 'Likely refers to insurance covering family-related risks (specifics unclear).';        $coverage->lob_id = '9';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Fidelity Bond';        $coverage->acronym = 'FIDB';         $coverage->description = 'Protection against losses due to fraudulent acts by employees.';        $coverage->lob_id = '4';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Fire, Lining, Explosion Aircraft';        $coverage->acronym = 'FLEA';         $coverage->description = 'Coverage for fire, explosion, and aircraft-related risks.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Flood Parametric';        $coverage->acronym = 'FPAR';         $coverage->description = 'A coverage that pays out automatically when a predetermined flood condition is met, such as exceeding a specific water level, rainfall amount, or flood depth, without requiring proof of physical damage.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Floor Plan';        $coverage->acronym = 'FLPN';         $coverage->description = 'Insurance for inventory financing arrangements often used by dealerships.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Funeral Expenses';        $coverage->acronym = 'FEXP';         $coverage->description = 'Coverage for costs associated with funerals and burials.';        $coverage->lob_id = '9';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Glass breakage, advertisement, stained glasses, domes and signals.';        $coverage->acronym = 'GADS';         $coverage->description = 'Insurance for damages to specialized glass installations and signage.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Health';        $coverage->acronym = 'HLT';         $coverage->description = 'General health insurance covering medical expenses.';        $coverage->lob_id = '8';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Homeowners Protection';        $coverage->acronym = 'HOP';         $coverage->description = 'Coverage for risks associated with owning a home, including property damage and liability.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Hull';        $coverage->acronym = 'HULL';         $coverage->description = 'Insurance for the physical structure of ships and boats.';        $coverage->lob_id = '2';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Hull & Cargo';        $coverage->acronym = 'HUC';         $coverage->description = 'Combined coverage for ships and the cargo they carry.';        $coverage->lob_id = '10';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Hull War';        $coverage->acronym = 'HWAR';         $coverage->description = 'Specific coverage for war-related risks to ships and boats.';        $coverage->lob_id = '2';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Hurricane Parametric';        $coverage->acronym = 'HPAR';         $coverage->description = 'Insurance paying out based on hurricane parameters rather than actual loss.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Internal Fraud';        $coverage->acronym = 'INFR';         $coverage->description = 'Protection against losses due to internal fraudulent activities.';        $coverage->lob_id = '14';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Key Man';        $coverage->acronym = 'KMP';         $coverage->description = 'Insurance covering the loss of key personnel critical to a business.';        $coverage->lob_id = '9';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Large & Complex Risks';        $coverage->acronym = 'LCR';         $coverage->description = 'Likely refers to coverage for large, complex industrial facilities (specifics unclear).';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Legal Expenses';        $coverage->acronym = 'LEXP';         $coverage->description = 'Coverage for legal costs arising from various legal actions.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Life';        $coverage->acronym = 'LIFE';         $coverage->description = 'General life insurance covering death benefits and related risks.';        $coverage->lob_id = '8';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Life & Health';        $coverage->acronym = 'LHLT';         $coverage->description = 'Likely a combined term for life and health insurance coverage.';        $coverage->lob_id = '9';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Livestock';        $coverage->acronym = 'LVS';         $coverage->description = 'Insurance for risks related to the health and safety of livestock animals.';        $coverage->lob_id = '1';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Loss of Profits';        $coverage->acronym = 'LOP';         $coverage->description = 'Coverage for lost income due to an insured event affecting business operations.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Loss of Warranty';        $coverage->acronym = 'LOW';         $coverage->description = 'Protection against losses resulting from the failure of a warranty.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Machinery Breakdown';        $coverage->acronym = 'MBD';         $coverage->description = 'Coverage for the repair or replacement of machinery following a breakdown.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Non-Damage Business Interruption';        $coverage->acronym = 'NDBI';         $coverage->description = 'Insurance for business interruption not caused by physical damage.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Pandemic Business Interruption';        $coverage->acronym = 'PBI';         $coverage->description = 'Coverage for business losses due to pandemics.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Personal Accident';        $coverage->acronym = 'PACC';         $coverage->description = 'Insurance providing benefits for accidental injury or death.';        $coverage->lob_id = '9';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Physical Damage';        $coverage->acronym = 'PHDA';         $coverage->description = 'General term for coverage against physical damage to property or equipment.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Political Risks';        $coverage->acronym = 'POLR';         $coverage->description = 'Coverage for risks associated with political events like expropriation or political violence.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Political Violence';        $coverage->acronym = 'POLV';         $coverage->description = 'Specific insurance for damage or loss due to politically motivated acts of violence.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Pollution Liability';        $coverage->acronym = 'PLL';         $coverage->description = 'Coverage for liabilities arising from environmental pollution.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Product Contamination';        $coverage->acronym = 'PCON';         $coverage->description = 'Insurance for losses due to the contamination of products.';        $coverage->lob_id = '14';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Product Recall';        $coverage->acronym = 'PRC';         $coverage->description = 'Coverage for costs associated with recalling defective or dangerous products.';        $coverage->lob_id = '14';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Quality or Defects in Material or Product';        $coverage->acronym = 'QDMP';         $coverage->description = 'Coverage for liabilities related to defects in materials or products.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Sabotage & Terrorism';        $coverage->acronym = 'SAT';         $coverage->description = 'Insurance against losses due to acts of sabotage or terrorism.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Storage and Transportation';        $coverage->acronym = 'STRN';         $coverage->description = 'Insurance for goods during storage and transit.';        $coverage->lob_id = '15';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Supplementary Expenses';        $coverage->acronym = 'SEXP';         $coverage->description = 'Coverage for additional costs incurred due to an insured event.';        $coverage->lob_id = '7';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Tent Plan';        $coverage->acronym = 'TENTP';         $coverage->description = 'Specific coverage term unclear (might need clarification).';        $coverage->lob_id = '11';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Terrorism';        $coverage->acronym = 'TER';         $coverage->description = 'Coverage for losses due to terrorist acts.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Theft';        $coverage->acronym = 'THF';         $coverage->description = 'Insurance against loss due to theft.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Third Party Liability';        $coverage->acronym = 'TPL';         $coverage->description = 'Coverage for liabilities to third parties for injury or damage caused by the insured.';        $coverage->lob_id = '14';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Total and Permanent Disability';        $coverage->acronym = 'TPD';         $coverage->description = 'Insurance providing benefits if the insured becomes totally and permanently disabled.';        $coverage->lob_id = '9';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'TPL-Environmental';        $coverage->acronym = 'TPLENV';         $coverage->description = 'Third Party Liability insurance specifically for environmental damage claims.';        $coverage->lob_id = '14';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'TPL-Errors & Omissions/ Professional Liability or Professional Indemnity';        $coverage->acronym = 'EOPI';         $coverage->description = 'Coverage for errors and omissions in professional services.';        $coverage->lob_id = '14';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'TPL-Finished Works';        $coverage->acronym = 'TPLFW';         $coverage->description = 'Liability coverage for completed construction projects.';        $coverage->lob_id = '14';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'TPL-Gradual Pollution';        $coverage->acronym = 'TPLGP';         $coverage->description = 'Coverage for liabilities arising from gradual pollution over time.';        $coverage->lob_id = '14';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'TPL-Litigation Abroad';        $coverage->acronym = 'TPLLA';         $coverage->description = 'Liability coverage for legal actions taken abroad.';        $coverage->lob_id = '14';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'TPL-Subjective';        $coverage->acronym = 'TPLSUB';         $coverage->description = 'Specific term unclear (might need clarification).';        $coverage->lob_id = '14';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'TPL-Terrorism';        $coverage->acronym = 'TPLTERR';         $coverage->description = 'Third Party Liability insurance specifically for terrorism-related claims.';        $coverage->lob_id = '14';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'TPL-Umbrella';        $coverage->acronym = 'TPLUMB';         $coverage->description = 'Umbrella liability insurance providing additional coverage above primary policies.';        $coverage->lob_id = '14';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Unemployment';        $coverage->acronym = 'UNEM';         $coverage->description = 'Coverage for loss of income due to unemployment.';        $coverage->lob_id = '9';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Violent Robbery';        $coverage->acronym = 'VROB';         $coverage->description = 'Insurance against losses due to violent robbery.';        $coverage->lob_id = '12';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = "Workers' Compensation";        $coverage->acronym = 'WCOM';         $coverage->description = 'Coverage for medical expenses and lost wages for workers injured on the job.';        $coverage->lob_id = '16';       $coverage->save(); 
        $coverage=new coverage();       $coverage->name = 'Debris Removal';        $coverage->acronym = 'DBRM';         $coverage->description = 'Covers the reasonable and necessary costs of removing debris from the insured premises following a covered physical loss or damage.';        $coverage->lob_id = '12';       $coverage->save(); 
    }
}
