<?php

namespace Database\Seeders;

use App\Models\CostScheme;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CschemePapillonSeeder2025 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250127-0001';        $CostScheme->index = '1';          $CostScheme->share = '0.998999989';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250127-0002';        $CostScheme->index = '2';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250127-0003';        $CostScheme->index = '3';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250127-0004';        $CostScheme->index = '4';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250127-0005';        $CostScheme->index = '5';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250127-0006';        $CostScheme->index = '6';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250127-0007';        $CostScheme->index = '7';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250127-0008';        $CostScheme->index = '8';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250127-0009';        $CostScheme->index = '9';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250127-0010';        $CostScheme->index = '10';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250127-0011';        $CostScheme->index = '11';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250127-0012';        $CostScheme->index = '12';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250203-0001';        $CostScheme->index = '1';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250204-0001';        $CostScheme->index = '1';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250204-0002';        $CostScheme->index = '2';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250204-0003';        $CostScheme->index = '3';          $CostScheme->share = '0.9999';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250205-0004';        $CostScheme->index = '4';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250206-0001';        $CostScheme->index = '1';          $CostScheme->share = '0.9999';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250206-0002';        $CostScheme->index = '2';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250206-0003';        $CostScheme->index = '3';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250209-0012';        $CostScheme->index = '12';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250210-0001';        $CostScheme->index = '1';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250210-0002';        $CostScheme->index = '2';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250210-0003';        $CostScheme->index = '3';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250210-0004';        $CostScheme->index = '4';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250210-0005';        $CostScheme->index = '5';          $CostScheme->share = '0.9999';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250211-0001';        $CostScheme->index = '1';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250211-0002';        $CostScheme->index = '2';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250211-0003';        $CostScheme->index = '3';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250211-0004';        $CostScheme->index = '4';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250211-0005';        $CostScheme->index = '5';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250225-0001';        $CostScheme->index = '1';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 
        $CostScheme=new CostScheme();          $CostScheme->id = 'SCHE-20250225-0002';        $CostScheme->index = '2';          $CostScheme->share = '1';            $CostScheme->agreement_type = 'Quota Share';         $CostScheme->description = 'Each and every loss, subject to the applicable annual aggregate.';         $CostScheme->created_at = date('Y-m-d',strtotime('2025-05-01'));         $CostScheme->updated_at = date('Y-m-d',strtotime('2025-05-01'));     $CostScheme->created_by_user = '15';      $CostScheme->save(); 

    }
}