<?php

namespace Database\Seeders;

use App\Models\invoice;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class InvoicesCellMayabSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        
        $invoice=new invoice();      $invoice->id = '4883600f-950e-41e9-9e90-905952d7f4c0';      $invoice->invoice_code = 'P-2010-01';        $invoice->issue_date = date('Y-m-d', strtotime('2010/11/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2010/11/26'));     $invoice->description = null;             $invoice->invoice_path = null;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2010/12/01'));         $invoice->amount = '223906.5';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = 'a738a6da-0b89-4ac4-87d0-a911f16bfcda';      $invoice->invoice_code = '2011-001';        $invoice->issue_date = date('Y-m-d', strtotime('2011/02/24'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2011/11/26'));     $invoice->description =  'Access fees - 2011  ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2011001.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2011/12/01'));         $invoice->amount = '187000';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '458a4918-842e-43f1-a076-95f6506ce304';      $invoice->invoice_code = 'P-2011-02';        $invoice->issue_date = date('Y-m-d', strtotime('2011/11/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2011/11/26'));     $invoice->description = null;             $invoice->invoice_path = null;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2011/12/01'));         $invoice->amount = '67500';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = 'cda06bb0-d194-489e-a354-099353b606dc';      $invoice->invoice_code = '2013-003';        $invoice->issue_date = date('Y-m-d', strtotime('2013/09/25'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2012/11/25'));     $invoice->description =  'Access fees for period 30 September 2012 – 30 March 2013: In respect of Auto Excess of Loss Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2013003.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2012/11/30'));         $invoice->amount = '18000';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '12074fb7-b30b-432c-a3a1-096c8f3529fb';      $invoice->invoice_code = '2013-004';        $invoice->issue_date = date('Y-m-d', strtotime('2013/09/25'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2012/11/26'));     $invoice->description =  'Access fees for period 31 December 2012 – 31 December 2013: In respect of Mega Empack Product Contamination Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2013004.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2012/12/01'));         $invoice->amount = '174108.42';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = 'bc20ffc8-4f81-485c-89f8-d179808f5797';      $invoice->invoice_code = 'P-2012-02';        $invoice->issue_date = date('Y-m-d', strtotime('2012/11/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2012/11/26'));     $invoice->description = null;             $invoice->invoice_path = null;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2012/12/01'));         $invoice->amount = '117000';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '6d0151f0-f9de-46f6-8edc-c9b0ba940064';      $invoice->invoice_code = 'P-2012-04';        $invoice->issue_date = date('Y-m-d', strtotime('2012/11/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2012/11/26'));     $invoice->description = null;             $invoice->invoice_path = null;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2012/12/01'));         $invoice->amount = '116517.5';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '69fa3f27-6260-41b1-a11c-0505a0110432';      $invoice->invoice_code = 'P-2012-05';        $invoice->issue_date = date('Y-m-d', strtotime('2012/11/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2012/11/26'));     $invoice->description = null;             $invoice->invoice_path = null;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2012/12/01'));         $invoice->amount = '128250';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '2f484cab-583e-4fd2-8dd1-25c488510e6c';      $invoice->invoice_code = '2014-001';        $invoice->issue_date = date('Y-m-d', strtotime('2014/01/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2014/01/15'));     $invoice->description =  'Access fees for period 31 December 2013 – 31 December 2014: In respect of Mega Empack Product Contamination Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2014001.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2013/12/01'));         $invoice->amount = '138389.445';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '8ecdf0f3-151a-4b3e-a195-a6fcdef4d09b';      $invoice->invoice_code = '2013-005';        $invoice->issue_date = date('Y-m-d', strtotime('2013/10/11'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2013/11/26'));     $invoice->description =  'Access fees for period 5 July 2013 – 5 July 2014: In respect of Financial Lines Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2013005.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2013/12/01'));         $invoice->amount = '117000';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '9c4be117-1864-4858-b5d3-fe70f133e0ff';      $invoice->invoice_code = '2014-003';        $invoice->issue_date = date('Y-m-d', strtotime('2014/01/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2014/01/15'));     $invoice->description =  'Access fees for period 28 December 2013 – 28 December 2014: In respect of Bepensa Hurricane Parametric Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2014003.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2013/12/01'));         $invoice->amount = '110373.75';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '3ff7c5d7-7e60-48d1-9dfb-85748e233cab';      $invoice->invoice_code = '2014-002';        $invoice->issue_date = date('Y-m-d', strtotime('2014/01/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2014/01/15'));     $invoice->description =  'Access fees for period 28 December 2013 – 28 December 2014: In respect of Bepensa Product Contamination Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2014002.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2013/12/01'));         $invoice->amount = '121487.625';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '2c1e212a-3e5b-48e6-993d-592e214ee435';      $invoice->invoice_code = 'P-2014-01';        $invoice->issue_date = date('Y-m-d', strtotime('2014/11/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2014/11/26'));     $invoice->description = null;             $invoice->invoice_path = null;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2014/12/01'));         $invoice->amount = '138389.4477';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '99f47329-4b02-4e01-a80a-20a5e1081a88';      $invoice->invoice_code = '2014-004';        $invoice->issue_date = date('Y-m-d', strtotime('2014/12/31'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2015/01/15'));     $invoice->description =  'Access fees for period 5 July 2014 – 5 July 2015: In respect of Financial Lines Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2014004.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2014/12/01'));         $invoice->amount = '83250';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '289210c5-f625-49a8-af1a-1735b857fa29';      $invoice->invoice_code = '2015-002';        $invoice->issue_date = date('Y-m-d', strtotime('2015/01/20'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2015/02/15'));     $invoice->description =  'Access fees for period 28 December 2014 – 28 December 2015: In respect of Bepensa Hurricane Parametric Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2015002.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2014/12/01'));         $invoice->amount = '110373.75';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = 'ce569e46-a041-4a48-8977-1dfe1feddfdf';      $invoice->invoice_code = '2015-001';        $invoice->issue_date = date('Y-m-d', strtotime('2015/01/20'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2015/02/15'));     $invoice->description =  'Access fees for period 28 December 2014 – 28 December 2015: In respect of Bepensa Product Contamination Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2015001.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2014/12/01'));         $invoice->amount = '121487.625';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '683df24e-1119-4dfb-958d-5a0f1e0054d8';      $invoice->invoice_code = '2015-003';        $invoice->issue_date = date('Y-m-d', strtotime('2015/06/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2016/07/06'));     $invoice->description =  'Access fees for period 28 February 2015 – 28 February 2016: In respect of Mega Empack Product Contamination Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2015003.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2016/07/11'));         $invoice->amount = '138389.4477';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = 'f40abc62-d040-4778-a57f-50bad4f6a022';      $invoice->invoice_code = '2015-006';        $invoice->issue_date = date('Y-m-d', strtotime('2015/11/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2016/03/27'));     $invoice->description =  'Access fees for period 1 August 2015 – 1 August 2016: In respect of Financial Lines Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2015006.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2016/04/01'));         $invoice->amount = '83250';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '0f61f57b-c116-4cd0-85bf-327df61420ba';      $invoice->invoice_code = '2015-006-R';        $invoice->issue_date = date('Y-m-d', strtotime('2015/11/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2016/03/27'));     $invoice->description = null;             $invoice->invoice_path = null;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2016/09/26'));         $invoice->amount = '9250';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Consulrisk, LLC';       $invoice->issuer_id = '4';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '7c4595b7-c94e-4967-82da-5c2e5807047e';      $invoice->invoice_code = '2015-009';        $invoice->issue_date = date('Y-m-d', strtotime('2015/12/29'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2016/07/06'));     $invoice->description =  'Access fees for period 28 December 2015 – 28 December 2016: In respect of Bepensa Hurricane Parametric Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2015009.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2016/07/11'));         $invoice->amount = '110373.75';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '596b2bdb-ef67-460c-8080-d317e178aa9c';      $invoice->invoice_code = '2015-009-R';        $invoice->issue_date = date('Y-m-d', strtotime('2015/12/29'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2016/07/06'));     $invoice->description = null;             $invoice->invoice_path = null;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2016/03/01'));         $invoice->amount = '30414.1';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Consulrisk, LLC';       $invoice->issuer_id = '4';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '21c22454-56d8-4820-b960-047b639f4c17';      $invoice->invoice_code = '2015-010';        $invoice->issue_date = date('Y-m-d', strtotime('2015/12/29'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2016/07/06'));     $invoice->description =  'Access fees for period 28 December 2015 – 28 December 2016: In respect of Bepensa Product Contamination Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2015010.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2016/07/11'));         $invoice->amount = '121487.625';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = 'c2fe688f-febb-44f0-a9cf-0290e7de0a72';      $invoice->invoice_code = '2015-010-R';        $invoice->issue_date = date('Y-m-d', strtotime('2015/12/29'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2016/07/06'));     $invoice->description = null;             $invoice->invoice_path = null;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2016/03/01'));         $invoice->amount = '33476.59';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Consulrisk, LLC';       $invoice->issuer_id = '4';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = 'a3d33e68-80b7-4ae7-a553-00a371a4791c';      $invoice->invoice_code = '2016-002';        $invoice->issue_date = date('Y-m-d', strtotime('2016/03/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2016/07/06'));     $invoice->description =  'Access fees for period 15 February 2016 – 15 February 2017: In respect of Mega Empack Product Contamination Reinsurance ' ;         $invoice->invoice_path =  'https://rmk-resources.s3.amazonaws.com/reinsurers/income_invoices/INV-RMIS2016002.pdf ' ;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2016/07/11'));         $invoice->amount = '131465.70045';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Rainmaker Insurance SCC in respect of Cell Mayab';       $invoice->issuer_id = '1';     $invoice->save(); 
        $invoice=new invoice();      $invoice->id = '832baa1d-8cc8-4a57-b3b5-7b1507040ead';      $invoice->invoice_code = '2016-002-R';        $invoice->issue_date = date('Y-m-d', strtotime('2016/03/01'));      $invoice->expected_due_date = date('Y-m-d', strtotime('2016/07/06'));     $invoice->description = null;             $invoice->invoice_path = null;          $invoice->status_id = '1';       $invoice->payment_date = date('Y-m-d', strtotime('2016/03/01'));         $invoice->amount = '36518.250125';        $invoice->exch_rate = '1';      $invoice->currency_id = '157';      $invoice->bill_to_id = 'Consulrisk, LLC';       $invoice->issuer_id = '4';     $invoice->save(); 
    }
}
