<?php

namespace Database\Seeders;

use App\Models\LiabilityStructure;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LiabilityStructureMayabSeeder2026 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '65' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '20000000' ;                             $LiabilityStructure->limit_desc =  'Each and every loss.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '30' ;                      $LiabilityStructure->deductible_desc =  'Days waiting' ;                        $LiabilityStructure->business_code =  '2026-MAY010-001' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '24' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '20000000' ;                             $LiabilityStructure->limit_desc =  'Each and every loss.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '30' ;                      $LiabilityStructure->deductible_desc =  'Days waiting' ;                        $LiabilityStructure->business_code =  '2026-MAY010-001' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '54' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '12500000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate. ' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible = null;                     $LiabilityStructure->deductible_desc = null;                       $LiabilityStructure->business_code =  '2026-MAY010-002' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '23' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '4000000' ;                             $LiabilityStructure->limit_desc =  'Each and every loss per insured and USD 15,000,000 in the annual aggregate.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '500000' ;                      $LiabilityStructure->deductible_desc =  'Each and every loss' ;                        $LiabilityStructure->business_code =  '2026-MAY010-003' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '41' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '4000000' ;                             $LiabilityStructure->limit_desc =  'Each and every loss per insured and USD 15,000,000 in the annual aggregate.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '500000' ;                      $LiabilityStructure->deductible_desc =  'Each and every loss' ;                        $LiabilityStructure->business_code =  '2026-MAY010-003' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '8' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '5000000' ;                             $LiabilityStructure->limit_desc =  'Per event but USD 10,000,000 in the annual aggregate. ' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '100000' ;                      $LiabilityStructure->deductible_desc =  'Each and every loss' ;                        $LiabilityStructure->business_code =  '2026-MAY010-004' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '62' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '5000000' ;                             $LiabilityStructure->limit_desc =  'Per event but USD 10,000,000 in the annual aggregate. ' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '7' ;                      $LiabilityStructure->deductible_desc =  'Days waiting' ;                        $LiabilityStructure->business_code =  '2026-MAY010-004' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '23' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '3000000' ;                             $LiabilityStructure->limit_desc =  'Per event but USD 10,000,000 in the annual aggregate. ' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '500000' ;                      $LiabilityStructure->deductible_desc =  'Each and every loss' ;                        $LiabilityStructure->business_code =  '2026-MAY010-005' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '41' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '3000000' ;                             $LiabilityStructure->limit_desc =  'Per event but USD 10,000,000 in the annual aggregate. ' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '500000' ;                      $LiabilityStructure->deductible_desc =  'Each and every loss' ;                        $LiabilityStructure->business_code =  '2026-MAY010-005' ;                         $LiabilityStructure->save(); 

    }
}