<?php

namespace Database\Seeders;

use App\Models\LiabilityStructure;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LiabilityStructureOmegaSeeder2026 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '1' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '31050000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate. ' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible = null;                     $LiabilityStructure->deductible_desc = null;                       $LiabilityStructure->business_code =  '2026-OME035-001' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '1' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '33999988.68' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate. ' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible = null;                     $LiabilityStructure->deductible_desc = null;                       $LiabilityStructure->business_code =  '2026-OME035-002' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '81' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '207000000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, in excess of the original deductibles.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '0.1' ;                      $LiabilityStructure->deductible_desc =  'Each and every loss with a minimum of MXN 20,000.00' ;                        $LiabilityStructure->business_code =  '2026-OME035-003' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '81' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '18000000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, in excess of the original deductibles.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '0.1' ;                      $LiabilityStructure->deductible_desc =  'Each and every loss with a minimum of MXN 20,000.00' ;                        $LiabilityStructure->business_code =  '2026-OME035-004' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '81' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '212068965.51' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, in excess of the original deductibles.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '0.1' ;                      $LiabilityStructure->deductible_desc =  'Each and every loss with a minimum of MXN 20,000.00' ;                        $LiabilityStructure->business_code =  '2026-OME035-005' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '81' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '45000000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, in excess of the original deductibles.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '0.1' ;                      $LiabilityStructure->deductible_desc =  'Each and every loss with a minimum of MXN 20,000.00' ;                        $LiabilityStructure->business_code =  '2026-OME035-006 ' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '81' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '40500000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, in excess of the original deductibles.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '0.1' ;                      $LiabilityStructure->deductible_desc =  'Each and every loss with a minimum of MXN 20,000.00' ;                        $LiabilityStructure->business_code =  '2026-OME035-007' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '1' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '212068965.51' ;                             $LiabilityStructure->limit_desc =  'Per event.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible = null;                     $LiabilityStructure->deductible_desc = null;                       $LiabilityStructure->business_code =  '2026-OME035-008' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '1' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '25311455.4' ;                             $LiabilityStructure->limit_desc =  'Per event.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible = null;                     $LiabilityStructure->deductible_desc = null;                       $LiabilityStructure->business_code =  '2026-OME035-009' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '1' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '64438272' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate. ' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible = null;                     $LiabilityStructure->deductible_desc = null;                       $LiabilityStructure->business_code =  '2026-OME035-010' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '81' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '64438272' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, in excess of the original deductibles.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '0.1' ;                      $LiabilityStructure->deductible_desc =  'Each and every loss with a minimum of MXN 20,000.00' ;                        $LiabilityStructure->business_code =  '2026-OME035-011' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '81' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '175000000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, in excess of the original deductibles.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '0.1' ;                      $LiabilityStructure->deductible_desc =  'Each and every loss with a minimum of MXN 20,000.00' ;                        $LiabilityStructure->business_code =  '2026-OME035-012' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '1' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '12500000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate. ' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible = null;                     $LiabilityStructure->deductible_desc = null;                       $LiabilityStructure->business_code =  '2026-OME035-013' ;                         $LiabilityStructure->save();  

    }
}