<?php

namespace Database\Seeders;

use App\Models\LiabilityStructure;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LiabilityStructureInvictusSeeder2026 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '25' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '25000000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, as a single and combined limit.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible = null;                     $LiabilityStructure->deductible_desc = null;                       $LiabilityStructure->business_code =  '2026-INV039-001' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '25' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '25000000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, as a single and combined limit.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible = null;                     $LiabilityStructure->deductible_desc = null;                       $LiabilityStructure->business_code =  '2026-INV039-002' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '25' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '10000000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, as a single and combined limit in excess of deductibles.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '7' ;                      $LiabilityStructure->deductible_desc =  'Days, with a minimum deductible of USD 150,000.00 each and every loss, and event.' ;                        $LiabilityStructure->business_code =  '2026-INV039-003' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '25' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '10000000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, as a single and combined limit in excess of deductibles.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '7' ;                      $LiabilityStructure->deductible_desc =  'Days, with a minimum deductible of USD 150,000.00 each and every loss, and event.' ;                        $LiabilityStructure->business_code =  '2026-INV039-004' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '25' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '25000000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, as a single and combined limit.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible = null;                     $LiabilityStructure->deductible_desc = null;                       $LiabilityStructure->business_code =  '2026-INV039-005' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '25' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '25000000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, as a single and combined limit.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible = null;                     $LiabilityStructure->deductible_desc = null;                       $LiabilityStructure->business_code =  '2026-INV039-006' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '25' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '10000000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, as a single and combined limit in excess of deductibles.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '7' ;                      $LiabilityStructure->deductible_desc =  'Days, with a minimum deductible of USD 150,000.00 each and every loss, and event.' ;                        $LiabilityStructure->business_code =  '2026-INV039-007' ;                         $LiabilityStructure->save(); 
        $LiabilityStructure=new LiabilityStructure();        $LiabilityStructure->index =  '1' ;                    $LiabilityStructure->coverage_id =  '25' ;                            $LiabilityStructure->cls =  '1' ;                      $LiabilityStructure->limit =  '10000000' ;                             $LiabilityStructure->limit_desc =  'Per event and in the annual aggregate, as a single and combined limit in excess of deductibles.' ;                             $LiabilityStructure->sublimit = null;                       $LiabilityStructure->sublimit_desc = null;                       $LiabilityStructure->deductible =  '7' ;                      $LiabilityStructure->deductible_desc =  'Days, with a minimum deductible of USD 150,000.00 each and every loss, and event.' ;                        $LiabilityStructure->business_code =  '2026-INV039-008' ;                         $LiabilityStructure->save(); 

    }
}