<?php

namespace Database\Seeders;

use App\Models\partner;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PartnersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $partner=new partner();         $partner->name = 'Active Capital Reinsurance, Ltd';        $partner->short_name = 'Active Re - [REC]';        $partner->acronym = 'ACT';          $partner->partner_types_id = '5';          $partner->country_id = '20';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Agroasemex S.A';        $partner->short_name = 'Agroasemex - [INC]';        $partner->acronym = 'AGR';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'AIG Insurance Company';        $partner->short_name = 'AIG Insurance - [INC]';        $partner->acronym = 'AIG';          $partner->partner_types_id = '3';          $partner->country_id = '236';         $partner->save(); 
        $partner=new partner();         $partner->name = 'AIG Seguros México, S.A. de C.V.';        $partner->short_name = 'AIG Seguros - [INC]';        $partner->acronym = 'AGM';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Aseguradora Patrimonial Daños, S.A.';        $partner->short_name = 'Patrimonial Daños - [INC]';        $partner->acronym = 'PATD';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Aseguradora Patrimonial Vida S.A. de C.V.';        $partner->short_name = 'Patrimonial Vida - [INC]';        $partner->acronym = 'PATV';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Aserta Seguros Vida, S.A. de C.V., Grupo Financiero Aserta';        $partner->short_name = 'Aserta Vida - [INC]';        $partner->acronym = 'ASE';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'ASV Argentina Salud Vida Y Patrimoniales Compañía de Seguros S.A.';        $partner->short_name = 'ASV Seguros - [INC]';        $partner->acronym = 'ASV';          $partner->partner_types_id = '3';          $partner->country_id = '11';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Austral Re Corredores De Reaseguros S.A.';        $partner->short_name = 'Austral Re - [REB]';        $partner->acronym = 'AUS';          $partner->partner_types_id = '4';          $partner->country_id = '11';         $partner->save(); 
        $partner=new partner();         $partner->name = 'AXA Seguros, S.A. de C.V.';        $partner->short_name = 'AXA Seguros - [INC]';        $partner->acronym = 'AXA';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Barents Re Reinsurance Company, Inc.';        $partner->short_name = 'Barents Re - [REC]';        $partner->acronym = 'BAS';          $partner->partner_types_id = '5';          $partner->country_id = '42';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Best Doctors Insurance Quote';        $partner->short_name = 'Best Doctors - [INC]';        $partner->acronym = 'BDS';          $partner->partner_types_id = '3';          $partner->country_id = '236';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Best Meridian Insurance Company';        $partner->short_name = 'Best Meridian - [REC]';        $partner->acronym = 'BMI';          $partner->partner_types_id = '5';          $partner->country_id = '236';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Direct Broker';        $partner->short_name = 'Direct Broker - [REB]';        $partner->acronym = 'DIR';          $partner->partner_types_id = '4';          $partner->country_id = '20';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Chubb Seguros Mexico S.A.';        $partner->short_name = 'Chubb Seguros - [INC]';        $partner->acronym = 'CHB';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Compañía de Seguros America Sociedad Anonima';        $partner->short_name = 'Seguros América - [INC]';        $partner->acronym = 'AME';          $partner->partner_types_id = '3';          $partner->country_id = '160';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Compañía Hispana de Seguros, S. A. (Seguros Inca)';        $partner->short_name = 'Seguros Inca - [INC]';        $partner->acronym = 'HISP';          $partner->partner_types_id = '3';          $partner->country_id = '75';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Consulrisk, LLC';        $partner->short_name = 'Consulrisk - [RIB]';        $partner->acronym = 'CSK';          $partner->partner_types_id = '2';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Crédito Hipotecario Nacional';        $partner->short_name = 'Crédito Hipotecario - [INC]';        $partner->acronym = 'CRH';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Crédito Hípotecario Nacional de Guatemala';        $partner->short_name = 'Hipotecario Guatemala - [INC]';        $partner->acronym = 'HNG';          $partner->partner_types_id = '3';          $partner->country_id = '92';         $partner->save(); 
        $partner=new partner();         $partner->name = 'El Sol de Paraguay Compañía de Seguros y Reaseguros S.A.';        $partner->short_name = 'El Sol Paraguay - [INC]';        $partner->acronym = 'SOL';          $partner->partner_types_id = '3';          $partner->country_id = '174';         $partner->save(); 
        $partner=new partner();         $partner->name = 'El Sol de Paraguay Compañía de Seguros y Reaseguros S.A.';        $partner->short_name = 'El Sol Paraguay - [REC]';        $partner->acronym = 'SOL';          $partner->partner_types_id = '5';          $partner->country_id = '174';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Eureka - Re SCC';        $partner->short_name = 'Eureka Re - [REC]';        $partner->acronym = 'ERK';          $partner->partner_types_id = '5';          $partner->country_id = '20';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Experta Aseguradora de Riesgos de Trabajo S.A.';        $partner->short_name = 'Experta Riesgos - [INC]';        $partner->acronym = 'EXP';          $partner->partner_types_id = '3';          $partner->country_id = '11';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Fianzas Avanza, S.A. de C.V.';        $partner->short_name = 'Fianzas Avanza - [INC]';        $partner->acronym = 'AVZ';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Ficohsa Seguros Sociedad Anónima';        $partner->short_name = 'Ficohsa Seguros - [INC]';        $partner->acronym = 'FCS';          $partner->partner_types_id = '3';          $partner->country_id = '100';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Gatekeeper Indemnity SCC';        $partner->short_name = 'Gatekeeper Indemnity - [REC]';        $partner->acronym = 'GKI';          $partner->partner_types_id = '5';          $partner->country_id = '20';         $partner->save(); 
        $partner=new partner();         $partner->name = 'General de Seguros S.A.B.';        $partner->short_name = 'General Seguros - [INC]';        $partner->acronym = 'GDS';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'GMX Seguros';        $partner->short_name = 'GMX Seguros - [INC]';        $partner->acronym = 'GMX';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Grupo Mexicano de Seguros, S.A. de C.V.';        $partner->short_name = 'Grupo Mexicano - [INC]';        $partner->acronym = 'GMS';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Grupo Nacional Provincial, S.A.B.';        $partner->short_name = 'GNP Seguros - [INC]';        $partner->acronym = 'GNP';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'HDI Seguros, S.A. de C.V.';        $partner->short_name = 'HDI Seguros - [INC]';        $partner->acronym = 'HDI';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'HIR Compañía de Seguros, S.A. de C.V.';        $partner->short_name = 'HIR Seguros - [INC]';        $partner->acronym = 'HIR';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Insignia Life S.A.de C.V.';        $partner->short_name = 'Insignia Life - [INC]';        $partner->acronym = 'INS';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Instituto Nacional de Seguros';        $partner->short_name = 'Instituto Seguros - [INC]';        $partner->acronym = 'INS';          $partner->partner_types_id = '3';          $partner->country_id = '54';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Instituto Nicaragüense de Seguros Y Reaseguros Iniser Seguros';        $partner->short_name = 'Iniser Seguros - [INC]';        $partner->acronym = 'NIC';          $partner->partner_types_id = '3';          $partner->country_id = '160';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Instituto Nicaragüense de Seguros Y Reaseguros Iniser Reaseguros';        $partner->short_name = 'Iniser Reaseguros - [REC]';        $partner->acronym = 'NIC';          $partner->partner_types_id = '5';          $partner->country_id = '160';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Interamericana de Seguros S.A.';        $partner->short_name = 'Interamericana Seguros - [INC]';        $partner->acronym = 'INT';          $partner->partner_types_id = '3';          $partner->country_id = '100';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Interprotección Intermediario de Seguros';        $partner->short_name = 'Interprotección - [RIB]';        $partner->acronym = 'INT';          $partner->partner_types_id = '2';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Istmo Compañía de Reaseguros, Inc.';        $partner->short_name = 'Istmo Re - [REC]';        $partner->acronym = 'IST';          $partner->partner_types_id = '5';          $partner->country_id = '172';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Julio C.';        $partner->short_name = 'Julio C - [IAG]';        $partner->acronym = 'JUL';          $partner->partner_types_id = '1';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Koston';        $partner->short_name = 'Koston - [RIB]';        $partner->acronym = 'KTN';          $partner->partner_types_id = '2';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'La Latinoamericana Seguros S.A.';        $partner->short_name = 'La Latinoamericana - [INC]';        $partner->acronym = 'LAT';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'La Previsora S.A. Compañía de Seguros';        $partner->short_name = 'La Previsora - [INC]';        $partner->acronym = 'PRE';          $partner->partner_types_id = '3';          $partner->country_id = '49';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Latina Seguros S.A.';        $partner->short_name = 'Latina Seguros - [INC]';        $partner->acronym = 'LSG';          $partner->partner_types_id = '3';          $partner->country_id = '65';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Mapfre Compañía de Seguros Generales de Chile S.A.';        $partner->short_name = 'Mapfre Chile - [INC]';        $partner->acronym = 'MCH';          $partner->partner_types_id = '3';          $partner->country_id = '45';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Mapfre México, S.A. Seguros';        $partner->short_name = 'Mapfre México - [INC]';        $partner->acronym = 'MFE';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Mapfre México, S.A. Reaseguro';        $partner->short_name = 'Mapfre Re - [REC]';        $partner->acronym = 'MFE';          $partner->partner_types_id = '5';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Nacional Seguros Patrimoniales Y Fianzas S.A.';        $partner->short_name = 'Nacional Seguros - [INC]';        $partner->acronym = 'SPA';          $partner->partner_types_id = '3';          $partner->country_id = '27';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Ocean International Reinsurance Company Limited';        $partner->short_name = 'Ocean Re - [REC]';        $partner->acronym = 'OCE';          $partner->partner_types_id = '5';          $partner->country_id = '172';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Orion Reinsurance (Bermuda) Ltd';        $partner->short_name = 'Orion Re - [REC]';        $partner->acronym = 'ORN';          $partner->partner_types_id = '5';          $partner->country_id = '25';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Positiva Compañía de Seguros S.A.';        $partner->short_name = 'Positiva Seguros - [INC]';        $partner->acronym = 'PST';          $partner->partner_types_id = '3';          $partner->country_id = '49';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Primero Seguros, S.A. de C.V.';        $partner->short_name = 'Primero Seguros - [INC]';        $partner->acronym = 'PRS';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Reaseguradora Patria, S.A.';        $partner->short_name = 'Patria Re - [REC]';        $partner->acronym = 'RPT';          $partner->partner_types_id = '5';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Reasinter Intermediario De Reaseguro S. A. De C. V';        $partner->short_name = 'Reasinter - [REB]';        $partner->acronym = 'RER';          $partner->partner_types_id = '4';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Rimac Seguros y Reaseguros, S.A.';        $partner->short_name = 'Rimac Seguros - [INC]';        $partner->acronym = 'RIM';          $partner->partner_types_id = '3';          $partner->country_id = '175';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Rimac Seguros y Reaseguros, S.A.';        $partner->short_name = 'Rimac Seguros - [REC]';        $partner->acronym = 'RIM';          $partner->partner_types_id = '5';          $partner->country_id = '175';         $partner->save(); 
        $partner=new partner();         $partner->name = 'SBS Seguros Colombia S.A.';        $partner->short_name = 'SBS Seguros - [INC]';        $partner->acronym = 'SBC';          $partner->partner_types_id = '3';          $partner->country_id = '49';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Afirme S. A. de C.V., Afirme Grupo Financiero';        $partner->short_name = 'Afirme Seguros - [INC]';        $partner->acronym = 'AFI';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Agromercantil, S.A.';        $partner->short_name = 'Agromercantil - [INC]';        $partner->acronym = 'AGM';          $partner->partner_types_id = '3';          $partner->country_id = '92';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Argos, S.A. de C.V.';        $partner->short_name = 'Argos Seguros - [INC]';        $partner->acronym = 'ARG';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Atlantida, S.A.';        $partner->short_name = 'Atlántida Seguros - [INC]';        $partner->acronym = 'ATA';          $partner->partner_types_id = '3';          $partner->country_id = '100';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Atlas, S. A.';        $partner->short_name = 'Atlas Seguros - [INC]';        $partner->acronym = 'ATL';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Azteca Daños, S.A. de C.V.';        $partner->short_name = 'Azteca Daños - [INC]';        $partner->acronym = 'AZD';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Azteca, S.A. de C.V.';        $partner->short_name = 'Azteca Seguros - [INC]';        $partner->acronym = 'AZT';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Azul S.A.';        $partner->short_name = 'Azul Seguros - [INC]';        $partner->acronym = 'AZL';          $partner->partner_types_id = '3';          $partner->country_id = '67';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Banorte, S.A. de C.V., Grupo Financiero Banorte';        $partner->short_name = 'Banorte Seguros - [INC]';        $partner->acronym = 'BNT';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros de Vida SURA Mexico S.A. de C.V.';        $partner->short_name = 'SURA Vida - [INC]';        $partner->acronym = 'SURA';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros el Potosi, S. A.';        $partner->short_name = 'Potosí Seguros - [INC]';        $partner->acronym = 'PTS';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros El Roble S.A.';        $partner->short_name = 'El Roble - [INC]';        $partner->acronym = 'ROB';          $partner->partner_types_id = '3';          $partner->country_id = '92';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros G&T S.A.';        $partner->short_name = 'G&T Seguros - [INC]';        $partner->acronym = 'G&T';          $partner->partner_types_id = '3';          $partner->country_id = '92';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros HSBC, S.A.';        $partner->short_name = 'HSBC Seguros - [INC]';        $partner->acronym = 'HSBC';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Inbursa, S.A., Grupo Financiero Inbursa';        $partner->short_name = 'Inbursa Seguros - [INC]';        $partner->acronym = 'INB';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Qualitas, C. A.';        $partner->short_name = 'Quálitas Seguros - [INC]';        $partner->acronym = 'QUA';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Reservas, S.A.';        $partner->short_name = 'Reservas Seguros - [INC]';        $partner->acronym = 'SGR';          $partner->partner_types_id = '3';          $partner->country_id = '64';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Sucre S.A.';        $partner->short_name = 'Sucre Seguros - [INC]';        $partner->acronym = 'SUC';          $partner->partner_types_id = '3';          $partner->country_id = '65';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros SURA (Antes Proseguros)';        $partner->short_name = 'SURA Seguros - [INC]';        $partner->acronym = 'SUR';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Universal, S.A.';        $partner->short_name = 'Universal Seguros - [INC]';        $partner->acronym = 'SGU';          $partner->partner_types_id = '3';          $partner->country_id = '64';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Som.Us Mexico Intermediario De Reaseguro S.A. de C.V.';        $partner->short_name = 'Somus México - [REB]';        $partner->acronym = 'SOM';          $partner->partner_types_id = '4';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Cooper Gay Martinez del Rio, Intermediario de Reaseguro, S.A. de C.V.';        $partner->short_name = 'Cooper Gay - [REB]';        $partner->acronym = 'CGM';          $partner->partner_types_id = '4';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Star Reinsurance Brokers, Intermediario De Reaseguro, S.A. de C.V.';        $partner->short_name = 'Star Re - [REB]';        $partner->acronym = 'STR';          $partner->partner_types_id = '4';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Summa Intermediario De Reaseguro, S.A. De C.V.';        $partner->short_name = 'Summa Re - [REB]';        $partner->acronym = 'SUM';          $partner->partner_types_id = '4';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'THB México S.A. de C.V. Intermediario de Reaseguro';        $partner->short_name = 'THB México - [REB]';        $partner->acronym = 'THB';          $partner->partner_types_id = '4';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Thona Seguros S.A. de C.V.';        $partner->short_name = 'Thona Seguros - [INC]';        $partner->acronym = 'THO';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Unibienes Seguros y Reaseguros Patrimoniales S.A.';        $partner->short_name = 'Unibienes Seguros - [INC]';        $partner->acronym = 'UNB';          $partner->partner_types_id = '3';          $partner->country_id = '27';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Unibienes Seguros y Reaseguros Patrimoniales S.A.';        $partner->short_name = 'Unibienes Seguros - [REC]';        $partner->acronym = 'UNB';          $partner->partner_types_id = '5';          $partner->country_id = '27';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Universales, S. A., Seguros';        $partner->short_name = 'Universales Seguros - [INC]';        $partner->acronym = 'UNI';          $partner->partner_types_id = '3';          $partner->country_id = '92';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Zurich Santander Seguros México S.A.';        $partner->short_name = 'Zurich Santander - [INC]';        $partner->acronym = 'ZST';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Zurich Santander Reaseguro México S.A.';        $partner->short_name = 'Zurich Santander Re - [REC]';        $partner->acronym = 'ZST';          $partner->partner_types_id = '5';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Zurich Vida Compañía de Seguros, S.A.';        $partner->short_name = 'Zurich Vida - [INC]';        $partner->acronym = 'ZUL';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Zurich, Compañía de Seguros, S.A.';        $partner->short_name = 'Zurich Seguros - [INC]';        $partner->acronym = 'ZUR';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Dynamic Reinsurance LLC';        $partner->short_name = 'Dynamic Re - [MGA]';        $partner->acronym = 'DYN';          $partner->partner_types_id = '6';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Rainmaker International';        $partner->short_name = 'Rainmaker - [INC]';        $partner->acronym = 'RMI';          $partner->partner_types_id = '3';          $partner->country_id = '236';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Client';        $partner->short_name = 'Client - [CLI]';        $partner->acronym = 'CLI';          $partner->partner_types_id = '7';          $partner->country_id = '251';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Global BRG, LLC';        $partner->short_name = 'Global BRG - [REB]';        $partner->acronym = 'GBL';          $partner->partner_types_id = '4';          $partner->country_id = '236';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Direct Channel';        $partner->short_name = 'Direct Channel - [CLI]';        $partner->acronym = 'DCL';          $partner->partner_types_id = '7';          $partner->country_id = '251';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Carpio Group';        $partner->short_name = 'Carpio Group - [CLI]';        $partner->acronym = 'CGO';          $partner->partner_types_id = '7';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Everest Re Group, Ltd.';        $partner->short_name = 'Everest Re - [REC]';        $partner->acronym = 'ERG';          $partner->partner_types_id = '5';          $partner->country_id = '25';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Pacific Life Reinsurance';        $partner->short_name = 'Pacific Re - [REC]';        $partner->acronym = 'PLR';          $partner->partner_types_id = '5';          $partner->country_id = '25';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Rainmaker Group.';        $partner->short_name = 'Rainmaker Group - [REC]';        $partner->acronym = 'RMK';          $partner->partner_types_id = '5';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Tokio Marine Kiln Syndicates Limited';        $partner->short_name = 'Tokio Marine - [REC]';        $partner->acronym = 'TMK';          $partner->partner_types_id = '5';          $partner->country_id = '235';         $partner->save(); 
        $partner=new partner();         $partner->name = 'XS Global';        $partner->short_name = 'XS Global - [MGA]';        $partner->acronym = 'XSG';          $partner->partner_types_id = '6';          $partner->country_id = '236';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Reinsurer';        $partner->short_name = 'Reinsurer - [REC]';        $partner->acronym = 'REI';          $partner->partner_types_id = '5';          $partner->country_id = '236';         $partner->save(); 
        $partner=new partner();         $partner->name = 'ACR Argentina';        $partner->short_name = 'ACR Argentina - [INC]';        $partner->acronym = 'ACR';          $partner->partner_types_id = '3';          $partner->country_id = '11';         $partner->save(); 
        $partner=new partner();         $partner->name = 'ACSA Seguros';        $partner->short_name = 'ACSA Seguros - [INC]';        $partner->acronym = 'ACS ';          $partner->partner_types_id = '3';          $partner->country_id = '67';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Alianza Garantía Seguros y Reaseguros S.A.';        $partner->short_name = 'Alianza Garantía - [INC]';        $partner->acronym = 'ALG';          $partner->partner_types_id = '3';          $partner->country_id = '174';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Aseguradora de Este SA';        $partner->short_name = 'Este Seguros - [INC]';        $partner->acronym = 'AES';          $partner->partner_types_id = '3';          $partner->country_id = '174';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Aseguradora del Sur';        $partner->short_name = 'Del Sur Seguros - [INC]';        $partner->acronym = 'ASU';          $partner->partner_types_id = '3';          $partner->country_id = '65';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Aseguradora General';        $partner->short_name = 'Aseguradora General - [INC]';        $partner->acronym = 'GEN';          $partner->partner_types_id = '3';          $partner->country_id = '92';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Aseguradora Solidaria';        $partner->short_name = 'Aseguradora Solidaria - [INC]';        $partner->acronym = 'ASO';          $partner->partner_types_id = '3';          $partner->country_id = '49';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Aseguradora Yacyreta S.A.';        $partner->short_name = 'Yacyretá Seguros - [INC]';        $partner->acronym = 'YAC';          $partner->partner_types_id = '3';          $partner->country_id = '174';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Banco de Seguros del Estado';        $partner->short_name = 'BSE Seguros - [INC]';        $partner->acronym = 'SES';          $partner->partner_types_id = '3';          $partner->country_id = '238';         $partner->save(); 
        $partner=new partner();         $partner->name = 'BANRESERVAS';        $partner->short_name = 'Banreservas - [INC]';        $partner->acronym = 'BAN';          $partner->partner_types_id = '3';          $partner->country_id = '64';         $partner->save(); 
        $partner=new partner();         $partner->name = 'BCI Seguros';        $partner->short_name = 'BCI Seguros - [INC]';        $partner->acronym = 'BCI';          $partner->partner_types_id = '3';          $partner->country_id = '45';         $partner->save(); 
        $partner=new partner();         $partner->name = 'British Caribbean Insurance Company';        $partner->short_name = 'British Caribbean - [INC]';        $partner->acronym = 'BRI';          $partner->partner_types_id = '3';          $partner->country_id = '112';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Compañía de Seguros Ecuatoriano Suiza de Seguros S.A.';        $partner->short_name = 'Ecuatoriano Suiza - [INC]';        $partner->acronym = 'ECU';          $partner->partner_types_id = '3';          $partner->country_id = '65';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Compañia De Seguros Generales Consorcio';        $partner->short_name = 'Consorcio Seguros - [INC]';        $partner->acronym = 'GEC';          $partner->partner_types_id = '3';          $partner->country_id = '45';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Compañia de Seguros Generales Contempora';        $partner->short_name = 'Contempora Seguros - [INC]';        $partner->acronym = 'GCO';          $partner->partner_types_id = '3';          $partner->country_id = '45';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Equinoccial';        $partner->short_name = 'Equinoccial Seguros - [INC]';        $partner->acronym = 'EQU';          $partner->partner_types_id = '3';          $partner->country_id = '65';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Federación Patronal de Seguros';        $partner->short_name = 'Federación Patronal - [INC]';        $partner->acronym = 'PAT';          $partner->partner_types_id = '3';          $partner->country_id = '11';         $partner->save(); 
        $partner=new partner();         $partner->name = 'FID Chile Seguros Generales S.A.';        $partner->short_name = 'FID Chile - [INC]';        $partner->acronym = 'FID';          $partner->partner_types_id = '3';          $partner->country_id = '45';         $partner->save(); 
        $partner=new partner();         $partner->name = 'General Accident Insurance Company';        $partner->short_name = 'General Accident - [INC]';        $partner->acronym = 'GEA';          $partner->partner_types_id = '3';          $partner->country_id = '112';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Guardian Group Fatum';        $partner->short_name = 'Guardian Fatum - [INC]';        $partner->acronym = 'FAT';          $partner->partner_types_id = '3';          $partner->country_id = '58';         $partner->save(); 
        $partner=new partner();         $partner->name = 'HDI Global';        $partner->short_name = 'HDI Global - [INC]';        $partner->acronym = 'HDG';          $partner->partner_types_id = '3';          $partner->country_id = '84';         $partner->save(); 
        $partner=new partner();         $partner->name = 'ICB Insurance Company';        $partner->short_name = 'ICB Insurance - [INC]';        $partner->acronym = 'ICB';          $partner->partner_types_id = '3';          $partner->country_id = '23';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Island Heritage Insurance Company';        $partner->short_name = 'Island Heritage - [INC]';        $partner->acronym = 'ISL';          $partner->partner_types_id = '3';          $partner->country_id = '42';         $partner->save(); 
        $partner=new partner();         $partner->name = 'La Boliviana Ciacruz de Seguros y Reaseguros S.A';        $partner->short_name = 'Boliviana Ciacruz - [INC]';        $partner->acronym = 'CIA';          $partner->partner_types_id = '3';          $partner->country_id = '27';         $partner->save(); 
        $partner=new partner();         $partner->name = 'La colonial';        $partner->short_name = 'La Colonial - [INC]';        $partner->acronym = 'COL';          $partner->partner_types_id = '3';          $partner->country_id = '64';         $partner->save(); 
        $partner=new partner();         $partner->name = 'La Consolidada de Seguros';        $partner->short_name = 'La Consolidada - [INC]';        $partner->acronym = 'CON';          $partner->partner_types_id = '3';          $partner->country_id = '174';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Meridional Seguros';        $partner->short_name = 'Meridional Seguros - [INC]';        $partner->acronym = 'MER';          $partner->partner_types_id = '3';          $partner->country_id = '11';         $partner->save(); 
        $partner=new partner();         $partner->name = 'La Paraguaya S.A. de Seguros y Reaseguros';        $partner->short_name = 'La Paraguaya - [INC]';        $partner->acronym = 'PAR';          $partner->partner_types_id = '3';          $partner->country_id = '174';         $partner->save(); 
        $partner=new partner();         $partner->name = 'MNK Seguros';        $partner->short_name = 'MNK Seguros - [INC]';        $partner->acronym = 'MNK';          $partner->partner_types_id = '3';          $partner->country_id = '54';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Multinational Insurance Company';        $partner->short_name = 'Multinational Insurance - [INC]';        $partner->acronym = 'MUL';          $partner->partner_types_id = '3';          $partner->country_id = '180';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Nacion Seguros y Reaseguros';        $partner->short_name = 'Nación Seguros - [INC]';        $partner->acronym = 'NAC';          $partner->partner_types_id = '3';          $partner->country_id = '11';         $partner->save(); 
        $partner=new partner();         $partner->name = 'One Alliance Insurance Corporation';        $partner->short_name = 'One Alliance - [INC]';        $partner->acronym = 'ONE';          $partner->partner_types_id = '3';          $partner->country_id = '180';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Opción Seguros SA';        $partner->short_name = 'Opción Seguros - [INC]';        $partner->acronym = 'OPS';          $partner->partner_types_id = '3';          $partner->country_id = '11';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Pacifico Seguros';        $partner->short_name = 'Pacífico Seguros - [INC]';        $partner->acronym = 'PAC';          $partner->partner_types_id = '3';          $partner->country_id = '175';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Reale Chile Seguros Generales S.A.';        $partner->short_name = 'Reale Chile - [INC]';        $partner->acronym = 'CHI';          $partner->partner_types_id = '3';          $partner->country_id = '45';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Renta Nacional Compania de Seguros Generales S.A.';        $partner->short_name = 'Renta Nacional - [INC]';        $partner->acronym = 'REN';          $partner->partner_types_id = '3';          $partner->country_id = '45';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Royal Seguros SA';        $partner->short_name = 'Royal Seguros - [INC]';        $partner->acronym = 'ROS';          $partner->partner_types_id = '3';          $partner->country_id = '174';         $partner->save(); 
        $partner=new partner();         $partner->name = 'RoyalStar Assurance Ltd';        $partner->short_name = 'RoyalStar Assurance - [INC]';        $partner->acronym = 'STA';          $partner->partner_types_id = '3';          $partner->country_id = '17';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Sancor Cooperativa de Seguros Limitada';        $partner->short_name = 'Sancor Seguros - [INC]';        $partner->acronym = 'SAN';          $partner->partner_types_id = '3';          $partner->country_id = '11';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Banrural';        $partner->short_name = 'Banrural Seguros - [INC]';        $partner->acronym = 'RUR';          $partner->partner_types_id = '3';          $partner->country_id = '100';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Crefisa SA';        $partner->short_name = 'Crefisa Seguros - [INC]';        $partner->acronym = 'CRE';          $partner->partner_types_id = '3';          $partner->country_id = '100';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros del País';        $partner->short_name = 'País Seguros - [INC]';        $partner->acronym = 'SEP';          $partner->partner_types_id = '3';          $partner->country_id = '100';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Fortaleza';        $partner->short_name = 'Fortaleza Seguros - [INC]';        $partner->acronym = 'SEF';          $partner->partner_types_id = '3';          $partner->country_id = '27';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Generales Sudamericana';        $partner->short_name = 'Sudamericana Seguros - [INC]';        $partner->acronym = 'SUD';          $partner->partner_types_id = '3';          $partner->country_id = '45';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Lafise';        $partner->short_name = 'Lafise Seguros - [INC]';        $partner->acronym = 'LAF';          $partner->partner_types_id = '3';          $partner->country_id = '160';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Seguros Ve Por Mas, S.A.';        $partner->short_name = 'Vepormas Seguros - [INC]';        $partner->acronym = 'BXM';          $partner->partner_types_id = '3';          $partner->country_id = '144';         $partner->save(); 
        $partner=new partner();         $partner->name = 'SMG Seguros';        $partner->short_name = 'SMG Seguros - [INC]';        $partner->acronym = 'SMG';          $partner->partner_types_id = '3';          $partner->country_id = '11';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Southbridge Insurance Company';        $partner->short_name = 'Southbridge Insurance - [INC]';        $partner->acronym = 'SOU';          $partner->partner_types_id = '3';          $partner->country_id = '45';         $partner->save(); 
        $partner=new partner();         $partner->name = 'Unnio Seguros Generales';        $partner->short_name = 'Unnio Seguros - [INC]';        $partner->acronym = 'UNN';          $partner->partner_types_id = '3';          $partner->country_id = '45';         $partner->save(); 

    }
}



