<?php

namespace Database\Seeders;

use App\Models\Transaction;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TransactionsYelmoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $transaction=new transaction();          $transaction->id = '68d2f248-8a1f-4f7f-99b7-78a8d1bb1e79';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2012-12-28'));       $transaction->op_document_id = '2012-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'd9a9ef08-f268-4723-a351-df6f2adb931b';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2013-07-01'));       $transaction->op_document_id = '2013-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'fadc2033-716a-44fc-a2cf-b7e9c66874a9';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2013-07-01'));       $transaction->op_document_id = '2013-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '069b2001-bc05-46a2-9bb1-17144d03d420';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2013-12-28'));       $transaction->op_document_id = '2013-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '73455421-1103-4345-9dc2-abe50620cda9';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2013-07-01'));       $transaction->op_document_id = '2013-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'a57c11c8-5cee-4ada-b4dc-2f08de5ab840';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2014-07-01'));       $transaction->op_document_id = '2014-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'dafb44fa-b861-49b8-a3fa-aec407dffcf8';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2014-07-01'));       $transaction->op_document_id = '2014-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '75e49351-6ea8-46c3-8f4d-4e4031f21160';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2014-12-28'));       $transaction->op_document_id = '2014-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '9b84be53-94e6-475c-b359-512b8448b221';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2015-07-01'));       $transaction->op_document_id = '2015-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'fbe4cc57-a277-4f9e-a1ce-d14fcd94fea5';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2015-07-01'));       $transaction->op_document_id = '2015-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'c83d5202-d07f-401b-a18d-6df9ecb5fc0b';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2015-07-01'));       $transaction->op_document_id = '2015-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '6a871c89-40fb-47d6-a305-af22725dfd9e';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2015-12-28'));       $transaction->op_document_id = '2015-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'db955046-35fe-4d2f-b947-7128d6cfa0e7';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2016-07-01'));       $transaction->op_document_id = '2016-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '69ea5566-2969-4625-b74e-38131e100a7d';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2016-07-01'));       $transaction->op_document_id = '2016-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '25b4076c-c29a-4f39-abc8-14f062fbf57a';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2016-07-01'));       $transaction->op_document_id = '2016-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'c5301ea8-1074-46c7-870a-8aaaafb2e33c';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2016-11-27'));       $transaction->op_document_id = '2016-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'b489e451-3187-4a12-a0dd-f9301d9cd090';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2017-07-01'));       $transaction->op_document_id = '2017-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '55e6c93e-3cac-440c-b2d4-198ba740ac9b';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2017-07-01'));       $transaction->op_document_id = '2017-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'aeb4f6ea-05c7-4fd8-99d7-04bae2b6bd11';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2017-07-01'));       $transaction->op_document_id = '2017-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '836ca339-e3af-4c11-8cc6-c34b2b01e9b7';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2017-12-28'));       $transaction->op_document_id = '2017-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '2c7acb58-7698-48b8-b402-d3df28c757c3';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2018-07-01'));       $transaction->op_document_id = '2018-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '36f6500e-b83f-45d3-99c9-77c6f2eb22db';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2018-07-01'));       $transaction->op_document_id = '2018-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '6ccc6401-1c85-41bd-800e-6d15d7b6f5d9';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2018-07-01'));       $transaction->op_document_id = '2018-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'bddbacd9-00fb-4360-b5fb-c9909a940f14';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2018-12-28'));       $transaction->op_document_id = '2018-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '3401bbf6-0eab-4897-b140-8f17ebb637a6';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2019-07-01'));       $transaction->op_document_id = '2019-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'c724c06d-eef4-4889-be5b-943d54fc39a7';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2019-07-01'));       $transaction->op_document_id = '2019-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '5ef6f7ba-1683-442e-b760-54912b7cec73';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2019-07-01'));       $transaction->op_document_id = '2019-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '026f2a01-b9f1-427f-afb8-6d83c2cf7ff7';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2019-12-28'));       $transaction->op_document_id = '2019-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '554c0aa3-da6f-4179-9044-ae3b1df8aa7c';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2019-12-28'));       $transaction->op_document_id = '2019-YEL002-005-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'f3a65599-9159-48a1-89d4-e517a46234a7';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2020-07-01'));       $transaction->op_document_id = '2020-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'bf596690-b35f-4d3d-a7b3-46670b0abeee';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2020-07-01'));       $transaction->op_document_id = '2020-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '608ed1a8-2f72-4f87-b0f9-1c527f1fe756';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2020-07-01'));       $transaction->op_document_id = '2020-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '27414e4c-b1f5-4e1e-a2af-406e8bf6e9c1';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2020-07-01'));       $transaction->op_document_id = '2020-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '95697883-7087-4757-a5bf-22534e3cb043';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2020-07-01'));       $transaction->op_document_id = '2020-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '5fdf7759-9a8e-4498-b671-e2c613708e89';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2020-12-28'));       $transaction->op_document_id = '2020-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '0a038bf4-c561-4eac-b14e-19cfc31cf252';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2020-12-28'));       $transaction->op_document_id = '2020-YEL002-005-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'bd4907fb-240c-4c80-a564-9d3e46ed9778';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2020-12-28'));       $transaction->op_document_id = '2020-YEL002-006-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '82ff2f46-bbc4-4870-bfe5-17f4e2099fb3';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2020-12-28'));       $transaction->op_document_id = '2020-YEL002-007-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '2f930dff-e0e3-464d-8949-c9e92a560f5c';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2021-10-08'));       $transaction->op_document_id = '2021-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '750f73f4-3a99-4571-b4e2-8c5318d7bbb2';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2021-11-08'));       $transaction->op_document_id = '2021-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '6ab21fa9-583e-4cac-a2ae-854679e1f91e';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2021-12-08'));       $transaction->op_document_id = '2021-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '5516e5ec-dcc6-497e-a46c-616f6f8dd458';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2021-08-27'));       $transaction->op_document_id = '2021-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'b84cc1ae-d007-438a-9f17-c0473e2338ea';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2021-08-20'));       $transaction->op_document_id = '2021-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'bd68c923-f0d4-4a01-8242-d45e78c66a6c';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-02-28'));       $transaction->op_document_id = '2021-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'f912150b-fc8b-4896-a6ab-9e57fa84b8d8';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-03-28'));       $transaction->op_document_id = '2021-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '999afeac-f357-4f26-bccb-5c00edda0488';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-04-28'));       $transaction->op_document_id = '2021-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'd78c9989-febe-45be-9b21-9d15b3905b95';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-02-28'));       $transaction->op_document_id = '2021-YEL002-005-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'e91181f1-f85d-48c5-ba80-1ceef0d0d773';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-03-28'));       $transaction->op_document_id = '2021-YEL002-005-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'db3accc0-b17e-454d-b703-eb8d2b15af6e';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-04-28'));       $transaction->op_document_id = '2021-YEL002-005-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '4f122348-3978-4722-80dc-d4cb6bf0e789';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-02-28'));       $transaction->op_document_id = '2021-YEL002-006-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '9bf2abea-c793-492b-a258-3812c57a1bd1';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-03-28'));       $transaction->op_document_id = '2021-YEL002-006-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'fe11fc63-35b5-45a0-9b77-dd96b930724a';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-04-28'));       $transaction->op_document_id = '2021-YEL002-006-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '5ad2cfdd-7c27-43f6-a3ae-63221ab73ee4';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-02-28'));       $transaction->op_document_id = '2021-YEL002-007-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '4a4f23af-5cc1-4fed-b3fc-7e8ebc2397c6';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-03-28'));       $transaction->op_document_id = '2021-YEL002-007-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'd581d4e1-14f2-4e84-8568-478b45d71a5d';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-04-28'));       $transaction->op_document_id = '2021-YEL002-007-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'd5d5317e-f7fd-4c5a-97a0-bd620990a107';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-09-29'));       $transaction->op_document_id = '2022-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'cd14af83-5ee2-436d-b8d0-3cb2e41f3547';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-10-28'));       $transaction->op_document_id = '2022-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '4bbdc229-31f4-481a-a616-49f3c2b0cea7';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-11-29'));       $transaction->op_document_id = '2022-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '45661aff-d3b1-4eb8-a161-99521ebd016d';         $transaction->index = '4';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-12-29'));       $transaction->op_document_id = '2022-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '0138aa97-e3e3-4866-b093-277ce0bc3b86';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-09-29'));       $transaction->op_document_id = '2022-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'a19d208b-fa24-4bb7-bf90-b5da465bf29d';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-10-28'));       $transaction->op_document_id = '2022-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '2cba6711-05d6-4f76-aff2-f6b44de5c8cc';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-11-29'));       $transaction->op_document_id = '2022-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '0c7cdc2e-9bd5-4a4a-96fc-5bf36b0415a7';         $transaction->index = '4';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-12-29'));       $transaction->op_document_id = '2022-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '83f12a6b-a7ef-40af-9f3d-eb7fc1893195';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-09-29'));       $transaction->op_document_id = '2022-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '0c06cfef-85e1-4354-b30b-ceb8b2b23f1e';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2023-01-27'));       $transaction->op_document_id = '2022-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'a454fe60-3e67-44d8-875f-c6058e0323c3';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2023-01-27'));       $transaction->op_document_id = '2022-YEL002-005-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'a5029cd8-43c5-42a3-85f8-69e22e83b698';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2023-01-27'));       $transaction->op_document_id = '2022-YEL002-006-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '657cae01-ac57-4387-bf2e-00e6886712b8';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2023-01-27'));       $transaction->op_document_id = '2022-YEL002-007-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'acdbc72e-3cb7-4a06-aefd-beb3a6f62834';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2022-10-28'));       $transaction->op_document_id = '2022-YEL002-008-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '347daae6-d92e-4ab7-8ff8-184ccda00c40';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2023-10-30'));       $transaction->op_document_id = '2023-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '72f358b7-e609-40d2-9271-5930ea9a262e';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2023-11-28'));       $transaction->op_document_id = '2023-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'd30f9ecd-d10b-4988-bc71-e12be27456f2';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2023-12-30'));       $transaction->op_document_id = '2023-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '4f86783f-90cc-4d59-aa7f-c42cb97ec9e3';         $transaction->index = '4';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-01-29'));       $transaction->op_document_id = '2023-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '29aedb30-9194-4da8-a5b2-86315333196d';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2023-09-29'));       $transaction->op_document_id = '2023-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'fbf092cc-c6d3-439a-8d1f-7031c9bf99cf';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2023-11-30'));       $transaction->op_document_id = '2023-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '86e19df2-ddf6-497b-b407-0013f322799c';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2023-12-29'));       $transaction->op_document_id = '2023-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '079451e6-42e6-4107-843b-ad52b8dd2a8c';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-01-29'));       $transaction->op_document_id = '2023-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '77b65c0c-2f8c-47c1-9fad-260dd60a2176';         $transaction->index = '4';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-02-29'));       $transaction->op_document_id = '2023-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '854026f6-19e0-483f-9880-c75ed66880c8';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2023-10-31'));       $transaction->op_document_id = '2023-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '7db6cbc5-a018-453d-8c47-bdb64cd1259b';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-03-27'));       $transaction->op_document_id = '2023-YEL002-005-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '8b86fdce-1b44-4b38-abc9-c091fb0ad8e6';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-04-26'));       $transaction->op_document_id = '2023-YEL002-005-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '711a72e1-ee70-41ba-b3bf-51dd52dfa7e2';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-05-27'));       $transaction->op_document_id = '2023-YEL002-005-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '75cc745d-bd1f-41fc-8848-007858099dca';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-03-27'));       $transaction->op_document_id = '2023-YEL002-006-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '8f5806d6-08dc-4560-b7aa-931f956a793b';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-04-26'));       $transaction->op_document_id = '2023-YEL002-006-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '41d0a6c6-2918-48a6-aede-6e34ba68dcd7';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-05-27'));       $transaction->op_document_id = '2023-YEL002-006-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '70e1bdfa-6535-4d57-9d49-cec4bd873e93';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-03-27'));       $transaction->op_document_id = '2023-YEL002-007-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'bc6571fb-754b-438b-88d0-0c7631218955';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-04-26'));       $transaction->op_document_id = '2023-YEL002-007-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'afce4aaa-0b43-45e9-9228-85c60f282893';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.333333333333333';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-05-27'));       $transaction->op_document_id = '2023-YEL002-007-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '3f520182-5399-459f-8956-d0403771ded4';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-10-30'));       $transaction->op_document_id = '2024-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'bc112d42-370f-4344-a165-586d176b72ae';         $transaction->index = '2';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-11-29'));       $transaction->op_document_id = '2024-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '11b4229b-5c76-448f-b9a9-3b184ad3a20a';         $transaction->index = '3';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-12-30'));       $transaction->op_document_id = '2024-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'e21275b9-1ebf-42df-b5e6-b277b6ccf2c1';         $transaction->index = '4';         $transaction->remmitance_code = null;          $transaction->proportion = '0.25';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2025-01-30'));       $transaction->op_document_id = '2024-YEL002-001-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'ea3f6d43-7710-4444-8fd1-0cb07107d0b1';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-12-23'));       $transaction->op_document_id = '2024-YEL002-002-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'c08a4ded-24fe-450b-9b22-4606c6f2d96b';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2024-12-23'));       $transaction->op_document_id = '2024-YEL002-003-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '284fb085-4e49-4177-bf44-f82ebb9c061e';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2025-04-24'));       $transaction->op_document_id = '2024-YEL002-004-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'b49b67d5-77fe-4e90-86e8-9a27cc805bb4';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2025-03-23'));       $transaction->op_document_id = '2024-YEL002-005-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '53ec0e22-6157-423c-9c01-99b0ebdfd105';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2025-04-27'));       $transaction->op_document_id = '2024-YEL002-006-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = 'b5cd7ebf-9839-48ed-856d-41b3891a452e';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2025-02-26'));       $transaction->op_document_id = '2024-YEL002-007-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save(); 
        $transaction=new transaction();          $transaction->id = '961ba66f-76be-4ae2-99ee-3261db806c5a';         $transaction->index = '1';         $transaction->remmitance_code = null;          $transaction->proportion = '1';         $transaction->exch_rate = '1';          $transaction->due_date = date('Y-m-d',strtotime('2025-02-26'));       $transaction->op_document_id = '2024-YEL002-008-01';       $transaction->transaction_status_id = '3';        $transaction->transaction_type_id = '1';        $transaction->save();  


    }
}
