<?php

namespace Database\Seeders;

use App\Models\Transaction;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TransactionsCellMayabSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $Transaction=new Transaction();          $Transaction->id = '993f0581-8985-49ba-ba40-bea327763638';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '0.55';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2011-01-15'));       $Transaction->op_document_id = '2010-CMY001-001-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = '0f81bd4b-a438-498c-8d35-bb606ba3c166';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '0.45';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2011-07-15'));       $Transaction->op_document_id = '2010-CMY001-001-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = 'eacacab4-2b1a-4220-98f9-41fb50816b92';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2012-02-15'));       $Transaction->op_document_id = '2011-CMY001-001-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = '47fa708b-0321-4faa-8893-8f89351965f3';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2011-11-15'));       $Transaction->op_document_id = '2011-CMY001-002-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = 'adcd203f-af58-48c3-ae98-e42da21f6a09';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2013-02-21'));       $Transaction->op_document_id = '2011-CMY001-002-02';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = 'c9f7b220-47f4-4db7-b4ec-6643f0a9ed0d';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2013-02-21'));       $Transaction->op_document_id = '2012-CMY001-001-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = 'a1dcfac7-30d0-496a-a9cf-566e616dd219';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2013-02-24'));       $Transaction->op_document_id = '2012-CMY001-002-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = '532d62ec-c8d6-478d-9523-c7c4156462a6';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2012-08-29'));       $Transaction->op_document_id = '2012-CMY001-003-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = '15251386-a43e-46f5-b19c-4e94ab792bc2';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2012-11-24'));       $Transaction->op_document_id = '2012-CMY001-004-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = 'cd355f8b-63a7-4818-8e2a-2752b12e936f';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2014-02-21'));       $Transaction->op_document_id = '2013-CMY001-001-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = '83bd6a5d-b0c6-4d03-813f-4f06dd9c29b4';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2014-02-21'));       $Transaction->op_document_id = '2013-CMY001-002-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = 'ae6c709a-01bc-4c02-b5a0-b0b9d192ab89';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2013-04-11'));       $Transaction->op_document_id = '2013-CMY001-003-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = '3ccddd8a-cb50-494a-89ea-d1aba9760d45';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2013-08-29'));       $Transaction->op_document_id = '2013-CMY001-004-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = 'c3a0420b-e192-48ea-904e-cc25977c6486';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2015-03-14'));       $Transaction->op_document_id = '2014-CMY001-001-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = 'c98a2bc2-1ede-45de-acda-91a8b657d4f2';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2015-03-14'));       $Transaction->op_document_id = '2014-CMY001-002-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = '65207f36-b87b-40e0-b9b3-3835c953043e';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2014-04-11'));       $Transaction->op_document_id = '2014-CMY001-003-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = 'f603f045-f091-4a6b-a3fe-0e3d06e3d80f';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2014-10-22'));       $Transaction->op_document_id = '2014-CMY001-004-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = 'd06d9176-7110-48c9-b209-ed197347f719';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2016-02-21'));       $Transaction->op_document_id = '2015-CMY001-001-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = '21f5fef2-fc26-452f-9d74-38aad37b76fb';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2016-02-21'));       $Transaction->op_document_id = '2015-CMY001-002-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = '8d862a07-5b2d-404e-9f52-80512c0152d9';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2015-05-29'));       $Transaction->op_document_id = '2015-CMY001-003-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = '3e8d80e2-99ef-4fd5-92fe-009322eb7007';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '1';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2015-10-16'));       $Transaction->op_document_id = '2015-CMY001-004-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = '9b80d982-67ac-46d9-a00d-b31687fb23f4';         $Transaction->index = '1';         $Transaction->remmitance_code = null;          $Transaction->proportion = '0.7';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2016-04-24'));       $Transaction->op_document_id = '2016-CMY001-001-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save(); 
        $Transaction=new Transaction();          $Transaction->id = 'dfea15d7-d970-44a0-950d-d1450444da87';         $Transaction->index = '2';         $Transaction->remmitance_code = null;          $Transaction->proportion = '0.3';         $Transaction->exch_rate = '1';          $Transaction->due_date = date('Y-m-d',strtotime('2016-04-24'));       $Transaction->op_document_id = '2016-CMY001-001-01';       $Transaction->transaction_status_id = '3';        $Transaction->transaction_type_id = '1';        $Transaction->save();  
    }
}
